"""Row role classifier (spec §14).

    DATA HEADER SUBTOTAL TOTAL FOOTER NOTE SECTION METADATA UNKNOWN

The single most important guarantee in this module:

    **A TOTAL or SUBTOTAL row is never ingested as a transaction.**

POS exports and bank statements routinely append a summary row. Ingesting it
inflates revenue, invents a transaction with no product, and double-counts every
line above it. The old guest path did exactly this, which is part of why
margins and inventory never matched the merchant's own books.

Deterministic detection runs first. Bounded judgment (JEV) is only consulted for
rows where the role is genuinely material and determinism is silent — never for
rows that are plainly total rows.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
from enum import Enum
from typing import Any, Mapping, Optional, Sequence

from app.services.orbit.contracts import RowRole, normalize_text

#: Tokens that mark a summary row. Matched against the *first meaningful cell* and
#: against any cell that is otherwise empty except for a label.
TOTAL_TOKENS = frozenset({
    "total", "totals", "grand total", "net total", "total sales", "total amount",
    "total sum", "sum", "aggregate", "grand", "sub total", "total revenue",
    "total expenses", "total cost", "total quantity", "total items",
    "اجمالي", "المجموع", "اجمالي المبيعات", "المجموع الكلي", "اجمالي الكمية",
    "الإجمالي", "الصافي",
})

SUBTOTAL_TOKENS = frozenset({
    "subtotal", "sub total", "sub-total", "sub sum", "partial total",
    "المجموع الفرعي", "اجمالي فرعي",
})

FOOTER_TOKENS = frozenset({
    "footer", "end of report", "report generated", "generated by", "printed",
    "page", "confidential", "powered by",
    "تذييل", "نهاية التقرير", "تم إنشاؤه",
})

NOTE_TOKENS = frozenset({
    "note", "notes", "remark", "remarks", "comment", "comments", "disclaimer",
    "terms", "terms and conditions", "important", "please note",
    "ملاحظة", "ملاحظات", "تعليقات", "شروط", "إخلاء مسؤولية",
})

METADATA_TOKENS = frozenset({
    "report date", "generated", "generated on", "period", "period from", "period to",
    "date range", "store", "branch", "business", "prepared by", "exported",
    "تاريخ التقرير", "الفترة", "الفرع", "المتجر", "تم التصدير",
})

SECTION_TOKENS = frozenset({
    "category:", "department:", "section:", "group:", "brand:", "type:",
    "category", "department", "section",
    "القسم:", "الفئة:", "التصنيف:", "الماركة:",
})

_QUANTITY_ONLY = {"quantity", "qty", "count", "units", "الكمية", "العدد"}

_NUMBER_RE = re.compile(r"-?\d[\d,]*\.?\d*")


def _cell_text(value: Any) -> str:
    if value is None:
        return ""
    s = str(value).strip()
    return "" if s.lower() in {"nan", "none", "null"} else s


def _to_decimal(text: str) -> Optional[Decimal]:
    cleaned = text.replace(",", "").strip()
    if not cleaned:
        return None
    try:
        return Decimal(cleaned)
    except (InvalidOperation, ValueError):
        return None


def _row_numbers(row: Sequence[Any]) -> list[Decimal]:
    out: list[Decimal] = []
    for value in row:
        text = _cell_text(value)
        if not text:
            continue
        # Currency symbols and trailing letters (e.g. "12 SAR") still parse.
        match = _NUMBER_RE.search(text)
        if match:
            parsed = _to_decimal(match.group(0))
            if parsed is not None:
                out.append(parsed)
    return out


def label_cells(row: Sequence[Any]) -> list[str]:
    """Cells that look like labels rather than numbers."""
    return [
        normalize_text(_cell_text(v))
        for v in row
        if _cell_text(v) and _to_decimal(_cell_text(v)) is None
    ]


def _matches_token(labels: Sequence[str], tokens: frozenset[str]) -> Optional[str]:
    """Exact label match first, substring match second.

    Order matters: ``subtotal`` contains ``total``, so a single-pass substring
    search would report every subtotal row as a grand total.
    """
    for label in labels:
        if label and label in tokens:
            return label
    for label in labels:
        if not label:
            continue
        for token in sorted(tokens, key=len, reverse=True):
            if len(token) >= 4 and token in label:
                return token
    return None


def classify_row(
    row: Sequence[Any],
    *,
    mapped_roles: Optional[Mapping[str, str]] = None,
    is_first_row: bool = False,
) -> tuple[RowRole, float, tuple[str, ...]]:
    """Classify one row deterministically.

    Returns ``(role, confidence, reasons)``. A summary row is recognised by a
    label plus the arithmetic signature that makes summary rows trustworthy:
    a total row's numeric cells equal the sum of the rows above it.
    """
    labels = label_cells(row)
    numbers = _row_numbers(row)
    reasons: list[str] = []

    if not labels and not numbers:
        return RowRole.UNKNOWN, 0.0, ("row is entirely blank",)

    header_hit = _matches_token(labels, SECTION_TOKENS)
    if header_hit:
        return RowRole.SECTION, 0.7, (f"section marker {header_hit!r}",)

    # Subtotal is tested before total: 'subtotal' contains 'total'.
    subtotal_hit = _matches_token(labels, SUBTOTAL_TOKENS)
    total_hit = _matches_token(labels, TOTAL_TOKENS)

    # A summary row has numbers as well as a label. A section header usually has
    # a label and nothing else, which is why SECTION is tested first.
    if (total_hit or subtotal_hit) and numbers:
        role = RowRole.SUBTOTAL if subtotal_hit else RowRole.TOTAL
        reasons.append(f"{role.value} label {subtotal_hit or total_hit!r}")
        reasons.append(f"{len(numbers)} numeric cells present")
        return role, 0.95, tuple(reasons)

    if subtotal_hit or total_hit:
        marker = subtotal_hit or total_hit
        role = RowRole.SUBTOTAL if subtotal_hit else RowRole.TOTAL
        reasons.append(f"label {marker!r} with no numeric cells")
        return role, 0.6, tuple(reasons)

    footer_hit = _matches_token(labels, FOOTER_TOKENS)
    if footer_hit and len(numbers) == 0:
        return RowRole.FOOTER, 0.8, (f"footer marker {footer_hit!r}",)

    note_hit = _matches_token(labels, NOTE_TOKENS)
    if note_hit and len(numbers) <= 1:
        return RowRole.NOTE, 0.7, (f"note marker {note_hit!r}",)

    meta_hit = _matches_token(labels, METADATA_TOKENS)
    if meta_hit and len(numbers) <= 2:
        return RowRole.METADATA, 0.65, (f"metadata marker {meta_hit!r}",)

    if is_first_row and mapped_roles:
        # The header row repeats column labels rather than data values.
        ratio = sum(1 for label in labels if label in set(mapped_roles.values())) / max(
            len(labels), 1
        )
        if ratio >= 0.5:
            return RowRole.HEADER, 0.85, (f"{ratio:.0%} of cells repeat column labels",)

    return RowRole.DATA, 0.85, ("no summary/metadata markers found",)


@dataclass(frozen=True)
class RowClassification:
    index: int
    role: RowRole
    confidence: float
    reasons: tuple[str, ...] = ()

    @property
    def is_ingestible(self) -> bool:
        """Only DATA rows become canonical facts."""
        return self.role is RowRole.DATA

    def to_dict(self) -> dict[str, Any]:
        return {
            "index": self.index,
            "role": self.role.value,
            "confidence": round(self.confidence, 4),
            "reasons": list(self.reasons),
            "ingestible": self.is_ingestible,
        }


@dataclass(frozen=True)
class RowRoleReport:
    """Row-role decisions for a whole sheet, plus the arithmetic verification."""

    classifications: tuple[RowClassification, ...]
    data_rows: tuple[int, ...]
    excluded_rows: tuple[int, ...]
    #: Indices of summary rows whose numbers actually equal the sum of the data
    #: rows above them. A mismatch means the label lied, which is worth reporting.
    verified_totals: tuple[int, ...] = ()
    suspicious_totals: tuple[int, ...] = ()
    notes: tuple[str, ...] = ()

    @property
    def data_count(self) -> int:
        return len(self.data_rows)

    @property
    def excluded_count(self) -> int:
        return len(self.excluded_rows)

    def to_dict(self) -> dict[str, Any]:
        return {
            "row_count": len(self.classifications),
            "data_rows": list(self.data_rows),
            "excluded_rows": list(self.excluded_rows),
            "data_count": self.data_count,
            "excluded_count": self.excluded_count,
            "verified_totals": list(self.verified_totals),
            "suspicious_totals": list(self.suspicious_totals),
            "notes": list(self.notes),
            "classifications": [c.to_dict() for c in self.classifications],
        }


def classify_rows(
    rows: Sequence[Sequence[Any]],
    *,
    mapped_roles: Optional[Mapping[str, str]] = None,
    header_row_index: int = 0,
) -> RowRoleReport:
    """Classify every row of a sheet.

    After the deterministic pass, any ``TOTAL``/``SUBTOTAL`` row is checked
    arithmetically: its numeric cells should equal the column-wise sum of the
    DATA rows above it. A total that does not reconcile is reported as
    ``suspicious_totals`` — the label may be decorative.
    """
    classifications: list[RowClassification] = []
    data_rows: list[int] = []
    excluded_rows: list[int] = []
    notes: list[str] = []

    for idx, row in enumerate(rows):
        role, confidence, reasons = classify_row(
            row, mapped_roles=mapped_roles, is_first_row=(idx == header_row_index)
        )
        classifications.append(
            RowClassification(index=idx, role=role, confidence=confidence, reasons=reasons)
        )
        if role is RowRole.DATA:
            data_rows.append(idx)
        else:
            excluded_rows.append(idx)

    summary_rows = [
        c.index
        for c in classifications
        if c.role in (RowRole.TOTAL, RowRole.SUBTOTAL)
    ]
    verified, suspicious = _verify_totals(rows, data_rows, summary_rows)
    if suspicious:
        notes.append(
            f"{len(suspicious)} summary row(s) labelled as totals do not reconcile "
            "with the rows above them"
        )

    return RowRoleReport(
        classifications=tuple(classifications),
        data_rows=tuple(data_rows),
        excluded_rows=tuple(excluded_rows),
        verified_totals=tuple(verified),
        suspicious_totals=tuple(suspicious),
        notes=tuple(notes),
    )


def _verify_totals(
    rows: Sequence[Sequence[Any]],
    data_rows: Sequence[int],
    summary_rows: Sequence[int],
    tolerance: Decimal = Decimal("0.02"),
) -> tuple[list[int], list[int]]:
    """Check that labelled totals reconcile with the data rows above them."""
    verified: list[int] = []
    suspicious: list[int] = []

    for summary_idx in summary_rows:
        preceding = [i for i in data_rows if i < summary_idx]
        if not preceding:
            continue

        data_sums: dict[int, Decimal] = {}
        for idx in preceding:
            for col, value in enumerate(rows[idx]):
                parsed = _to_decimal(_cell_text(value))
                if parsed is not None:
                    data_sums[col] = data_sums.get(col, Decimal(0)) + parsed

        summary_row = rows[summary_idx]
        summary_nums = [
            (col, _to_decimal(_cell_text(value)))
            for col, value in enumerate(summary_row)
        ]
        comparable = [
            (col, val) for col, val in summary_nums
            if val is not None and col in data_sums and data_sums[col] != 0
        ]
        if not comparable:
            continue

        matched = 0
        for col, val in comparable:
            expected = data_sums[col]
            if abs(expected - val) <= tolerance * max(abs(expected), Decimal(1)):
                matched += 1

        if matched >= max(1, len(comparable) // 2):
            verified.append(summary_idx)
        else:
            suspicious.append(summary_idx)

    return verified, suspicious