"use client";

// ShaderBackground — generated by the 21st.dev Shader Builder
// ("Dithering"). Zero dependencies: one WebGL canvas that fills its
// parent. Drop it behind your content with
// <div className="relative"><ShaderBackground className="absolute inset-0" />…
// Adapted from Paper Shaders: https://shaders.paper.design/dithering
// Paper Shaders is licensed under Apache-2.0.
//
// Nazmak tuning: two first-class ramps for one engine — the dark world
// (obsidian → black teal → deep teal → gold → rare ivory) and the light world
// (ivory core → gold sheen → soft teal → obsidian accent). The field maps to
// the palette with the histogram centre on the DOMINANT colour (obsidian on
// index 3 in dark, ivory on index 3 in light) and gold as its own upper band
// (~20% of the visual language in both modes, spec §22 §66) — verified against
// the canvas by the colour-QA probe, not assumed.

import { useEffect, useRef } from "react"
import type { UniverseStateKind } from "./data"

const VERT = `attribute vec2 a_position;
void main() {
  gl_Position = vec4(a_position, 0.0, 1.0);
}`

const FRAG = `#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

uniform vec3 u_colors[8];
// Seven packed vectors + eight colour vectors = 15 fragment uniform vectors,
// one below WebGL1's guaranteed minimum. Macros preserve the public u_* API.
uniform vec4 u_scene;      // resolution.xy, time, colour count
uniform vec4 u_shape;      // scale, intensity, paramA, warp
uniform vec4 u_surface;    // detail, contrast, brightness, saturation
uniform vec4 u_finish;     // hue, vignette, blur, grain
uniform vec4 u_transform;  // seed, rotation, drift, OKLab toggle
uniform vec4 u_space;      // offset.xy, pointer.xy
uniform vec4 u_cursor;

#define u_resolution u_scene.xy
#define u_time u_scene.z
#define u_colorCount u_scene.w
#define u_scale u_shape.x
#define u_intensity u_shape.y
#define u_paramA u_shape.z
#define u_warp u_shape.w
#define u_detail u_surface.x
#define u_contrast u_surface.y
#define u_brightness u_surface.z
#define u_saturation u_surface.w
#define u_hue u_finish.x
#define u_vignette u_finish.y
#define u_blur u_finish.z
#define u_grain u_finish.w
#ifdef GL_FRAGMENT_PRECISION_HIGH
#define u_seed u_transform.x
#else
// Keep hash inputs inside mediump's guaranteed ±2^14 range.
#define u_seed mod(u_transform.x, 31.0)
#endif
#define u_rotate u_transform.y
#define u_drift u_transform.z
#define u_oklab u_transform.w
#define u_offset u_space.xy
#define u_mouse u_space.zw
#define u_cursorPresence u_cursor.x
#define u_cursorEffect u_cursor.y
#define u_cursorStrength u_cursor.z
#define u_cursorRadius u_cursor.w

float hash21(vec2 p) {
#ifndef GL_FRAGMENT_PRECISION_HIGH
  p = mod(p, 31.0);
#endif
  p = fract(p * vec2(234.34, 435.345));
  p += dot(p, p + 34.23);
  return fract(p.x * p.y);
}

// Even, un-structured white noise for film grain (Dave Hoskins hash12). The
// multiply hash above is fine for value noise but shows a faint axis-aligned
// mesh at integer fragment coords, which reads as a net over flat areas.
float grainHash(vec2 p) {
  vec3 p3 = fract(vec3(p.xyx) * 0.1031);
  p3 += dot(p3, p3.yzx + 33.33);
  return fract((p3.x + p3.y) * p3.z);
}

vec2 hash22(vec2 p) {
#ifndef GL_FRAGMENT_PRECISION_HIGH
  p = mod(p, 31.0);
#endif
  float n = sin(dot(p, vec2(41.0, 289.0)));
  return fract(vec2(15731.743, 7892.321) * n);
}

float noise(vec2 p) {
  vec2 i = floor(p);
  vec2 f = fract(p);
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(
    mix(hash21(i), hash21(i + vec2(1.0, 0.0)), u.x),
    mix(hash21(i + vec2(0.0, 1.0)), hash21(i + vec2(1.0, 1.0)), u.x),
    u.y);
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p = p * 2.03 + vec2(17.0, 9.2);
    a *= 0.5;
  }
  return v;
}

// --- OKLab colour mixing (perceptual), gated by u_oklab -----------------------
vec3 srgbToLinear(vec3 c) {
  return mix(c / 12.92, pow((c + 0.055) / 1.055, vec3(2.4)),
    step(0.04045, c));
}
vec3 linearToSrgb(vec3 c) {
  // max() guards the sRGB branch: out-of-gamut OKLab interpolations can send a
  // channel negative, and pow(negative, …) is NaN which mix()/step() would
  // then propagate. The linear branch clips such channels to 0 downstream.
  return mix(c * 12.92, 1.055 * pow(max(c, vec3(0.0)), vec3(1.0 / 2.4)) - 0.055,
    step(0.0031308, c));
}
vec3 linToOklab(vec3 c) {
  float l = 0.4122214708 * c.r + 0.5363325363 * c.g + 0.0514459929 * c.b;
  float m = 0.2119034982 * c.r + 0.6806995451 * c.g + 0.1073969566 * c.b;
  float s = 0.0883024619 * c.r + 0.2817188376 * c.g + 0.6299787005 * c.b;
  l = pow(max(l, 0.0), 1.0 / 3.0);
  m = pow(max(m, 0.0), 1.0 / 3.0);
  s = pow(max(s, 0.0), 1.0 / 3.0);
  return vec3(
    0.2104542553 * l + 0.7936177850 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s);
}
vec3 oklabToLin(vec3 c) {
  float l = c.x + 0.3963377774 * c.y + 0.2158037573 * c.z;
  float m = c.x - 0.1055613458 * c.y - 0.0638541728 * c.z;
  float s = c.x - 0.0894841775 * c.y - 1.2914855480 * c.z;
  l = l * l * l; m = m * m * m; s = s * s * s;
  return vec3(
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s);
}
vec3 mixColour(vec3 a, vec3 b, float t) {
  if (u_oklab > 0.5) {
    vec3 la = linToOklab(srgbToLinear(a));
    vec3 lb = linToOklab(srgbToLinear(b));
    return clamp(linearToSrgb(oklabToLin(mix(la, lb, t))), 0.0, 1.0);
  }
  return mix(a, b, t);
}

// Mix through the recipe colours; x is clamped to 0..1. WebGL1 forbids
// dynamic uniform indexing in fragment shaders, hence the constant loop.
vec3 palette(float x) {
  float n = max(u_colorCount - 1.0, 1.0);
  float f = clamp(x, 0.0, 1.0) * n;
  vec3 col = u_colors[0];
  for (int i = 0; i < 7; i++) {
    if (float(i) < n)
      col = mixColour(col, u_colors[i + 1],
        smoothstep(0.0, 1.0, clamp(f - float(i), 0.0, 1.0)));
  }
  return col;
}

vec3 hueRotate(vec3 col, float a) {
  const mat3 toYIQ = mat3(0.299, 0.596, 0.211,
                          0.587, -0.274, -0.523,
                          0.114, -0.322, 0.312);
  const mat3 toRGB = mat3(1.0, 1.0, 1.0,
                          0.956, -0.272, -1.106,
                          0.621, -0.647, 1.703);
  vec3 yiq = toYIQ * col;
  float ca = cos(a), sa = sin(a);
  yiq = vec3(yiq.x, yiq.y * ca - yiq.z * sa, yiq.y * sa + yiq.z * ca);
  return toRGB * yiq;
}

vec3 shade(vec2 uv, vec2 p, float t) {
  float cells = mix(180.0, 28.0, u_paramA);
  vec2 pixel = floor(uv * cells);
  float field = fbm(p * (1.7 + u_intensity * 4.0) + vec2(t * 0.08, -t * 0.05));
  float threshold = fract(dot(pixel, vec2(0.75487766, 0.56984029)));
  float steps = mix(2.0, 7.0, u_intensity);
  float dithered = floor(field * steps + threshold) / steps;
  return palette(dithered);
}

void main() {
  vec2 uv = gl_FragCoord.xy / u_resolution.xy;
  vec2 screenUv = uv;
  vec2 p = (gl_FragCoord.xy - 0.5 * u_resolution.xy)
    / min(u_resolution.x, u_resolution.y);
  float cursorMask = 0.0;

  // Cursor modes 1–3 are local distortions. Push shifts the same screen-space
  // coordinates before field transforms, so Zoom/Rotate don't change its feel.
  if (u_cursorPresence > 0.001) {
    // u_mouse is normalized to -1..1 in canvas space. Convert it to the same
    // aspect-corrected screen space as p so effects stay under the cursor.
    vec2 cursor = (0.5 * u_mouse * u_resolution.xy)
      / min(u_resolution.x, u_resolution.y);
    vec2 cursorDelta = p - cursor;
    if (u_cursorEffect < 0.5) {
      p += cursor * u_cursorPresence * u_cursorStrength * 0.55;
    } else {
      float cursorDistance = length(cursorDelta);
      vec2 cursorDirection = cursorDelta / max(cursorDistance, 0.0001);
      cursorMask = u_cursorPresence
        * (1.0 - smoothstep(0.0, u_cursorRadius, cursorDistance));
      if (u_cursorEffect < 1.5) {
        p -= cursorDirection * cursorMask * u_cursorStrength * 0.24;
      } else if (u_cursorEffect < 2.5) {
        float cursorAngle = cursorMask * u_cursorStrength * 2.2;
        float cc = cos(cursorAngle), cs = sin(cursorAngle);
        p = cursor + mat2(cc, -cs, cs, cc) * cursorDelta;
      } else if (u_cursorEffect < 3.5) {
        float ripple = sin(
          cursorDistance / max(u_cursorRadius, 0.001) * 18.0 - u_time * 5.0);
        p -= cursorDirection * ripple * cursorMask * u_cursorStrength * 0.07;
      }
    }
  }

  // Keep presets that read uv (rather than p) in the same warped space.
  uv = p * min(u_resolution.x, u_resolution.y) / u_resolution.xy + 0.5;
  p *= u_scale;
  // Field transform: rotate, pan, pointer push, slow drift.
  if (abs(u_rotate) > 0.0001) {
    float cr = cos(u_rotate), sr = sin(u_rotate);
    p = mat2(cr, -sr, sr, cr) * p;
  }
  p += u_offset;
  if (u_drift > 0.0001)
    p += u_drift * vec2(sin(u_time * 0.31), cos(u_time * 0.23));
  // Organic domain warp.
  if (u_warp > 0.0) {
    p += u_warp * (vec2(
      fbm(p * u_detail + u_seed),
      fbm(p * u_detail + vec2(5.2, 1.3))) - 0.5);
  }
  // Shade, with an optional soft 5-tap blur.
  vec3 col;
  if (u_blur > 0.0) {
    float e = u_blur;
    float pe = e * u_scale;
    vec2 uvE = vec2(e) * min(u_resolution.x, u_resolution.y) / u_resolution.xy;
    col  = shade(uv, p, u_time) * 0.36;
    col += shade(uv + vec2(uvE.x, 0.0), p + vec2(pe, 0.0), u_time) * 0.16;
    col += shade(uv - vec2(uvE.x, 0.0), p - vec2(pe, 0.0), u_time) * 0.16;
    col += shade(uv + vec2(0.0, uvE.y), p + vec2(0.0, pe), u_time) * 0.16;
    col += shade(uv - vec2(0.0, uvE.y), p - vec2(0.0, pe), u_time) * 0.16;
  } else {
    col = shade(uv, p, u_time);
  }
  // Post: contrast, saturation, hue, brightness, vignette, grain.
  if (abs(u_contrast - 1.0) > 0.0001)
    col = (col - 0.5) * u_contrast + 0.5;
  if (abs(u_saturation - 1.0) > 0.0001) {
    float luma = dot(col, vec3(0.299, 0.587, 0.114));
    col = mix(vec3(luma), col, u_saturation);
  }
  if (abs(u_hue) > 0.0001)
    col = hueRotate(col, u_hue);
  if (abs(u_brightness) > 0.0001)
    col += u_brightness;
  if (u_vignette > 0.0001) {
    float vd = length(screenUv - 0.5) * 1.41421356;
    col *= 1.0 - u_vignette * smoothstep(0.35, 1.0, vd);
  }
  if (u_cursorPresence > 0.001 && u_cursorEffect > 3.5)
    col += (vec3(0.18) + col * 0.12) * cursorMask * u_cursorStrength;
  if (u_grain > 0.0001)
    col += (grainHash(
      gl_FragCoord.xy + vec2(u_seed * 17.0, u_seed * 31.0)) - 0.5) * u_grain;
  gl_FragColor = vec4(clamp(col, 0.0, 1.0), 1.0);
}
`

export type ShaderTheme = "dark" | "light";

export interface ShaderParams {
  colorCount: number;
  scale: number;
  intensity: number;
  paramA: number;
  warp: number;
  detail: number;
  contrast: number;
  brightness: number;
  saturation: number;
  hue: number;
  vignette: number;
  blur: number;
  grain: number;
  seed: number;
  rotate: number;
  offsetX: number;
  offsetY: number;
  drift: number;
  cursorEnabled: boolean;
  cursorEffect: number;
  cursorStrength: number;
  cursorRadius: number;
  oklab: number;
  timeScale: number;
}

// Two art-directed ramps for one engine (spec §17–§21). Each palette maps the
// noise field 0..1 → atmosphere. Ordering matters: WARM IVORY REFERENCE —
// the darkest region of the canvas sits on the LOW tail of the field, the
// bulk (histogram centre) must land on the DOMINANT colour, and gold occupies
// the upper-middle/high band as its own material ~20% of the visual language.
//
// DARK:  centre = obsidian depth → teal structure → gold filaments → rare ivory.
// LIGHT: centre = warm ivory → gold sheen → soft teal structure → obsidian accent.
// Repeated colours WIDEN a band; oklab interpolation (u_oklab) keeps the
// teal→gold transitions clean instead of muddy olive.
export const PALETTES: Record<ShaderTheme, number[][]> = {
  dark: [
    [0.012, 0.075, 0.075], // #031313 black teal floor (structure in the lows)
    [0.008, 0.035, 0.035], // #020909 obsidian floor
    [0.008, 0.035, 0.035], // #020909 obsidian floor (widens the dominant dark core)
    [0.008, 0.035, 0.035], // #020909 obsidian — histogram centre = dominant
    [0.024, 0.173, 0.165], // #062C2A deep teal
    [0.435, 0.282, 0.067], // #6F4811 warm dark gold (teal→gold bridge)
    [0.710, 0.482, 0.125], // #B57B20 warm gold — value thread
    [0.910, 0.878, 0.812], // #E8E0CF warm ivory (rare peak)
  ],
  light: [
    [0.043, 0.216, 0.208], // #0B3735 deep teal — obsidian-adjacent accent
    [0.176, 0.467, 0.439], // #2D7770 soft teal structure
    [0.902, 0.878, 0.824], // #E6E0D2 warm limestone ivory
    [0.953, 0.937, 0.898], // #F3EFE5 warm pearl ivory — histogram centre dominant
    [0.933, 0.914, 0.863], // #EEE9DC warm ivory
    [0.725, 0.490, 0.122], // #B97D1F antique gold — value thread
    [0.788, 0.580, 0.196], // #C99432 warm gold
    [0.886, 0.733, 0.420], // #E2BD6B bright metallic gold highlight
  ],
};

// Silent, organic motion in both modes (spec §23–§26). Light mode uses a
// softer vignette and lower saturation so the field stays airy, never heavy.
export const PARAMS: Record<ShaderTheme, ShaderParams> = {
  dark: {
    colorCount: 8,
    scale: 1.26,
    intensity: 0.35,
    paramA: 0.28,
    warp: 0.05,
    detail: 1.824,
    contrast: 1.02,
    brightness: 0,
    saturation: 0.95,
    hue: 0.0,
    vignette: 0.16,
    blur: 0.01,
    grain: 0.022,
    seed: 1.0,
    rotate: 0.0,
    offsetX: 0,
    offsetY: 0,
    drift: 0.015,
    cursorEnabled: false,
    cursorEffect: 2.0,
    cursorStrength: 0.65,
    cursorRadius: 0.46,
    oklab: 1,
    timeScale: 0.18,
  },
  light: {
    colorCount: 8,
    scale: 1.3,
    intensity: 0.32,
    paramA: 0.26,
    warp: 0.05,
    detail: 1.8,
    contrast: 1.05,
    brightness: 0,
    saturation: 0.9,
    hue: 0.0,
    vignette: 0.05,
    blur: 0.012,
    grain: 0.018,
    seed: 1.0,
    rotate: 0.0,
    offsetX: 0,
    offsetY: 0,
    drift: 0.012,
    cursorEnabled: false,
    cursorEffect: 2.0,
    cursorStrength: 0.65,
    cursorRadius: 0.46,
    oklab: 1,
    timeScale: 0.18,
  },
};

/**
 * Per-state param modifiers (spec §17): non-destructive adjustments that layer
 * on top of the current theme's base params. The atmosphere shifts in response
 * to the universe state without palette changes or context re-creation.
 */
export const STATE_MODIFIERS: Partial<Record<UniverseStateKind, Partial<ShaderParams>>> = {
  domain:  { intensity: 0.40, scale: 1.35 },
  nazmos:  { drift: 0.025 },
  audit:   { grain: 0.012, vignette: 0.20 },
  company: { saturation: 0.80 },
};

function maybeLerp(a: number[], b: number[], t: number): number[] {
  return [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, a[2] + (b[2] - a[2]) * t];
}

const pendingContextReleases = new WeakMap<HTMLCanvasElement, number>()

export function ShaderBackground({ className, theme, state }: { className?: string; theme: ShaderTheme; state?: UniverseStateKind }) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  // Palette morph state — theme switches crossfade u_colors over ~0.8s so the
  // environment "moves" between the two worlds instead of blinking (spec §39/§60).
  const paletteFromRef = useRef<number[][] | null>(null)
  const paletteToRef = useRef<number[][] | null>(null)
  const paletteTRef = useRef(1)
  const currentParamsRef = useRef<ShaderParams>(PARAMS.dark)
  const applyThemeRef = useRef<((next: ShaderTheme) => void) | null>(null)
  const applyStateRef = useRef<((state: UniverseStateKind) => void) | null>(null)
  const stateRef = useRef<UniverseStateKind>("universe")
  // Keep the initial mount theme reachable inside the one-shot engine effect
  // without forcing context re-creation (the engine is never rebuilt on switch).
  // `useRef(theme)` fixes its value to the mount frame.
  const themeRef = useRef<ShaderTheme>(theme)

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    const pendingRelease = pendingContextReleases.get(canvas)
    if (pendingRelease !== undefined) window.clearTimeout(pendingRelease)
    pendingContextReleases.delete(canvas)
    const gl = canvas.getContext("webgl", { antialias: false })
    if (!gl) return

    const compile = (type: number, src: string) => {
      const s = gl.createShader(type)!
      gl.shaderSource(s, src)
      gl.compileShader(s)
      return s
    }
    const program = gl.createProgram()!
    const vertexShader = compile(gl.VERTEX_SHADER, VERT)
    const fragmentShader = compile(gl.FRAGMENT_SHADER, FRAG)
    gl.attachShader(program, vertexShader)
    gl.attachShader(program, fragmentShader)
    gl.linkProgram(program)
    gl.deleteShader(vertexShader)
    gl.deleteShader(fragmentShader)
    gl.useProgram(program)

    const buf = gl.createBuffer()
    gl.bindBuffer(gl.ARRAY_BUFFER, buf)
    gl.bufferData(
      gl.ARRAY_BUFFER,
      new Float32Array([-1, -1, 3, -1, -1, 3]),
      gl.STATIC_DRAW,
    )
    const loc = gl.getAttribLocation(program, "a_position")
    gl.enableVertexAttribArray(loc)
    gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0)

    const uni = {
      colors: gl.getUniformLocation(program, "u_colors"),
      scene: gl.getUniformLocation(program, "u_scene"),
      shape: gl.getUniformLocation(program, "u_shape"),
      surface: gl.getUniformLocation(program, "u_surface"),
      finish: gl.getUniformLocation(program, "u_finish"),
      transform: gl.getUniformLocation(program, "u_transform"),
      space: gl.getUniformLocation(program, "u_space"),
      cursor: gl.getUniformLocation(program, "u_cursor"),
    }

    // Theme-aware uniform pipeline: non-colour params switch immediately, the
    // 8-colour ramp crossfades so a theme change morphs the environment.
    const uploadPalette = (colors: number[][]) => {
      gl.uniform3fv(uni.colors, new Float32Array(colors.flat()))
    }
    const applyParams = (p: ShaderParams) => {
      gl.uniform4f(
        uni.shape,
        p.scale,
        p.intensity,
        p.paramA,
        p.warp,
      )
      gl.uniform4f(
        uni.surface,
        p.detail,
        p.contrast,
        p.brightness,
        p.saturation,
      )
      gl.uniform4f(
        uni.finish,
        p.hue,
        p.vignette,
        p.blur,
        p.grain,
      )
      gl.uniform4f(
        uni.transform,
        p.seed,
        p.rotate,
        p.drift,
        p.oklab,
      )
      gl.uniform4f(
        uni.cursor,
        0,
        p.cursorEffect,
        p.cursorStrength,
        p.cursorRadius,
      )
      currentParamsRef.current = p
    }
    const applyTheme = (next: ShaderTheme) => {
      const to = PALETTES[next].map((c) => [...c])
      const from = paletteFromRef.current ?? PALETTES.dark.map((c) => [...c])
      paletteFromRef.current = from
      paletteToRef.current = to
      const base = PARAMS[next]
      const mod = STATE_MODIFIERS[stateRef.current] ?? {}
      applyParams({ ...base, ...mod })
      paletteTRef.current =
        JSON.stringify(from) === JSON.stringify(to) ? 1 : 0
      requestRender()
    }
    applyThemeRef.current = applyTheme

    // State sensitivity: non-destructive param overlay so the atmosphere shifts
    // in response to the universe state without palette changes (spec §17).
    const applyStateToShader = (s: UniverseStateKind) => {
      stateRef.current = s
      const base = PARAMS[themeRef.current]
      const mod = STATE_MODIFIERS[s] ?? {}
      applyParams({ ...base, ...mod })
      requestRender()
    }
    applyStateRef.current = applyStateToShader

    // Initial upload: present the target theme instantly (no load-time morph).
    const mountTheme = themeRef.current
    paletteFromRef.current = PALETTES[mountTheme].map((c) => [...c])
    paletteToRef.current = PALETTES[mountTheme].map((c) => [...c])
    paletteTRef.current = 1
    applyParams(PARAMS[mountTheme])
    uploadPalette(PALETTES[mountTheme])

    let targetX = 0
    let targetY = 0
    let targetPresence = 0
    let mouseX = 0
    let mouseY = 0
    let cursorPresence = 0
    let pointerKnown = false
    let pointerClientX = 0
    let pointerClientY = 0
    let bounds = canvas.getBoundingClientRect()
    let raf = 0
    let lastNow: number | null = null
    let visible = document.visibilityState === "visible"
    let inView = true
    let disposed = false
    const start = performance.now()
    const timeAnimated = Math.abs(PARAMS.dark.timeScale) > 0.0001

    const resizeCanvas = () => {
      const dpr = Math.min(window.devicePixelRatio || 1, 2)
      const rawWidth = Math.max(1, Math.round(bounds.width * dpr))
      const rawHeight = Math.max(1, Math.round(bounds.height * dpr))
      const pixelScale = Math.min(
        1,
        Math.sqrt(2_000_000 / Math.max(1, rawWidth * rawHeight)),
      )
      const width = Math.max(1, Math.round(rawWidth * pixelScale))
      const height = Math.max(1, Math.round(rawHeight * pixelScale))
      if (canvas.width !== width || canvas.height !== height) {
        canvas.width = width
        canvas.height = height
        gl.viewport(0, 0, width, height)
      }
    }

    function requestRender() {
      if (!disposed && visible && inView && raf === 0) {
        raf = requestAnimationFrame(render)
      }
    }

    const updatePointerTarget = () => {
      if (!pointerKnown) return
      if (bounds.width === 0 || bounds.height === 0) return
      const inside =
        pointerClientX >= bounds.left &&
        pointerClientX <= bounds.right &&
        pointerClientY >= bounds.top &&
        pointerClientY <= bounds.bottom
      if (!inside) {
        targetPresence = 0
        requestRender()
        return
      }
      const nextX = ((pointerClientX - bounds.left) / bounds.width) * 2 - 1
      const nextY = -(((pointerClientY - bounds.top) / bounds.height) * 2 - 1)
      if (targetPresence === 0 && cursorPresence < 0.01) {
        mouseX = nextX
        mouseY = nextY
      }
      targetX = nextX
      targetY = nextY
      targetPresence = 1
      requestRender()
    }
    const onPointerMove = (event: PointerEvent) => {
      pointerKnown = true
      pointerClientX = event.clientX
      pointerClientY = event.clientY
      bounds = canvas.getBoundingClientRect()
      updatePointerTarget()
    }
    const onPointerLeave = () => {
      pointerKnown = false
      targetPresence = 0
      requestRender()
    }
    const updateLayout = () => {
      bounds = canvas.getBoundingClientRect()
      resizeCanvas()
      updatePointerTarget()
      requestRender()
    }
    window.addEventListener("resize", updateLayout)
    if (PARAMS.dark.cursorEnabled) {
      window.addEventListener("pointermove", onPointerMove, { passive: true })
      window.addEventListener("pointercancel", onPointerLeave)
      window.addEventListener("scroll", updateLayout, true)
      window.addEventListener("blur", onPointerLeave)
      document.documentElement.addEventListener("pointerleave", onPointerLeave)
    }

    const resizeObserver = new ResizeObserver(updateLayout)
    resizeObserver.observe(canvas)
    const intersectionObserver = new IntersectionObserver(([entry]) => {
      inView = entry?.isIntersecting ?? true
      if (inView) requestRender()
      else if (raf !== 0) {
        cancelAnimationFrame(raf)
        raf = 0
        lastNow = null
      }
    })
    intersectionObserver.observe(canvas)
    const onVisibilityChange = () => {
      visible = document.visibilityState === "visible"
      if (visible) requestRender()
      else if (raf !== 0) {
        cancelAnimationFrame(raf)
        raf = 0
        lastNow = null
      }
    }
    document.addEventListener("visibilitychange", onVisibilityChange)

    const render = (now: number) => {
      raf = 0
      if (disposed || !visible || !inView) return
      const dt = lastNow === null ? 0 : Math.min((now - lastNow) / 1000, 0.1)
      lastNow = now
      const follow = 1 - Math.exp(-12 * dt)
      mouseX += (targetX - mouseX) * follow
      mouseY += (targetY - mouseY) * follow
      cursorPresence += (targetPresence - cursorPresence) * follow
      resizeCanvas()
      const width = canvas.width
      const height = canvas.height
      const p = currentParamsRef.current
      // Palette morph: crossfade the active 8-colour ramp toward theme.
      const to = paletteToRef.current ?? PALETTES.dark
      const from = paletteFromRef.current ?? PALETTES.dark
      let switching = paletteTRef.current < 1
      if (switching) {
        paletteTRef.current = Math.min(1, paletteTRef.current + dt / 0.8)
        const e = paletteTRef.current
        const eased = e * e * (3 - 2 * e)
        paletteFromRef.current = from.map((c, i) => maybeLerp(c, to[i], eased))
        gl.uniform3fv(uni.colors, new Float32Array(paletteFromRef.current.flat()))
      } else {
        gl.uniform3fv(uni.colors, new Float32Array(to.flat()))
      }
      gl.uniform4f(
        uni.scene,
        width,
        height,
        ((now - start) / 1000) * p.timeScale,
        p.colorCount,
      )
      gl.uniform4f(
        uni.space,
        p.offsetX,
        p.offsetY,
        mouseX,
        mouseY,
      )
      gl.uniform4f(
        uni.cursor,
        p.cursorEnabled ? cursorPresence : 0,
        p.cursorEffect,
        p.cursorStrength,
        p.cursorRadius,
      )
      gl.drawArrays(gl.TRIANGLES, 0, 3)
      const pointerSettling =
        Math.abs(targetX - mouseX) > 0.001 ||
        Math.abs(targetY - mouseY) > 0.001 ||
        Math.abs(targetPresence - cursorPresence) > 0.001
      if (switching) requestRender()
      else if (timeAnimated || pointerSettling) requestRender()
      else lastNow = null
    }
    requestRender()
    return () => {
      disposed = true
      cancelAnimationFrame(raf)
      resizeObserver.disconnect()
      intersectionObserver.disconnect()
      document.removeEventListener("visibilitychange", onVisibilityChange)
      window.removeEventListener("resize", updateLayout)
if (PARAMS.dark.cursorEnabled) {
        window.removeEventListener("pointermove", onPointerMove)
        window.removeEventListener("pointercancel", onPointerLeave)
        window.removeEventListener("scroll", updateLayout, true)
        window.removeEventListener("blur", onPointerLeave)
        document.documentElement.removeEventListener(
          "pointerleave",
          onPointerLeave,
        )
      }
      gl.deleteBuffer(buf)
      gl.deleteProgram(program)
      const releaseTimer = window.setTimeout(() => {
        if (pendingContextReleases.get(canvas) !== releaseTimer) return
        pendingContextReleases.delete(canvas)
        gl.getExtension("WEBGL_lose_context")?.loseContext()
        canvas.width = 1
        canvas.height = 1
      }, 0)
      pendingContextReleases.set(canvas, releaseTimer)
      applyThemeRef.current = null
      applyStateRef.current = null
    }
  }, [])

  // Sync the shader with the active theme. The engine is never destroyed —
  // switching crossfades the palette and swaps the non-colour params.
  useEffect(() => {
    applyThemeRef.current?.(theme)
  }, [theme])

  // State sensitivity: shift the atmosphere in response to the universe state.
  useEffect(() => {
    applyStateRef.current?.(state ?? "universe")
  }, [state])

  return (
    <canvas
      ref={canvasRef}
      data-shader-theme={theme}
      className={className}
      style={{ display: "block", width: "100%", height: "100%" }}
    />
  )
}