"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowLeft, ArrowRight, BadgeCheck, CheckCircle2, Coffee, FileSpreadsheet, Loader2, MessageCircle, Milk, Pill, RefreshCw, ShoppingBasket, Store, XCircle } from "lucide-react";

type DemoStep = "before" | "choose" | "upload" | "mapping" | "scan" | "audit" | "whatsapp" | "dashboard" | "weekly" | "cta";
type ActionStatus = "pending" | "approved" | "rejected";
type ActionType = "stockout" | "price" | "transfer" | "deadstock" | "expiry";

interface DemoAction { id:string; type:ActionType; title:string; titleAr:string; message:string; recommendation:string; value:number; recovery:number; consequence:string; approveLabel:string; rejectLabel:string; status:ActionStatus; }
interface InventoryRow { item:string; branch:string; daysLeft:string; risk:"Critical"|"High"|"Medium"|"Low"; action:string; }
interface Scenario { id:string; label:string; labelAr:string; icon:any; businessName:string; city:string; branches:number; description:string; files:string[]; columns:{source:string; mapped:string}[]; moneyAtRisk:number; deadStock:number; stockoutRiskValue:number; marginLeak:number; avoidablePurchases:number; healthScore:number; inventory:InventoryRow[]; actions:DemoAction[]; }

const formatSar = (v:number) => new Intl.NumberFormat("en-SA",{style:"currency",currency:"SAR",maximumFractionDigits:0}).format(v);
const scanSteps = ["Reading 90 days of sales", "Matching SKUs", "Calculating daily velocity", "Finding dead stock", "Predicting stockouts", "Detecting margin leakage", "Preparing WhatsApp actions"];
const baseColumns = [
  {source:"Product Name", mapped:"Item Name"}, {source:"Qty Sold", mapped:"Quantity"}, {source:"Sale Date", mapped:"Date"},
  {source:"Sell Price", mapped:"Selling Price"}, {source:"Stock On Hand", mapped:"Current Stock"}, {source:"Cost", mapped:"Cost Price"},
];
const makeAction = (id:string,type:ActionType,title:string,titleAr:string,message:string,recommendation:string,value:number,recovery:number,consequence:string,approveLabel:string): DemoAction => ({id,type,title,titleAr,message,recommendation,value,recovery,consequence,approveLabel,rejectLabel:"❌ Reject",status:"pending"});

const scenarios:Scenario[] = [
  {id:"baqala",label:"Baqala / Mini Market",labelAr:"بقالة",icon:ShoppingBasket,businessName:"Al-Nahda Mini Market",city:"Buraidah",branches:1,description:"Daily essentials, dairy, water, snacks, and household items.",files:["baqala_sales_90_days.csv","baqala_inventory_current.xlsx","supplier_prices_optional.csv"],columns:baseColumns,moneyAtRisk:43800,deadStock:17400,stockoutRiskValue:11800,marginLeak:8400,avoidablePurchases:6200,healthScore:76,inventory:[{item:"Fresh Milk 1L",branch:"Main Store",daysLeft:"1.8 days",risk:"Critical",action:"Reorder 96 units"},{item:"Water 330ml Pack",branch:"Main Store",daysLeft:"2.4 days",risk:"High",action:"Reorder before Thursday"},{item:"Chips Mix Box",branch:"Main Store",daysLeft:"38 days",risk:"Medium",action:"Reduce next order"}],actions:[makeAction("baqala-milk","stockout","Milk stockout risk","تنبيه نفاد الحليب","Fresh Milk 1L may finish in 1.8 days.","Reorder 96 units · Estimated cost: SAR 672",672,1100,"Purchase order draft created for review.","✅ Approve Reorder"),makeAction("baqala-water","stockout","Weekend water risk","تنبيه مياه قبل نهاية الأسبوع","Water packs may run low before Friday demand.","Reorder 60 packs · Estimated cost: SAR 900",900,1400,"Weekend stockout risk marked protected.","✅ Approve Reorder"),makeAction("baqala-dead","deadstock","Dead stock found","مخزون راكد","SAR 17,400 is tied in slow-moving items.","Create discount bundle for 14 SKUs this week.",17400,4200,"Discount bundle task created.","✅ Approve Bundle")]},
  {id:"dates",label:"Date Shop",labelAr:"متجر تمور",icon:Store,businessName:"Qassim Premium Dates",city:"Buraidah",branches:2,description:"Premium Sukari, Khalas, Ajwa, gifts, and Ramadan demand spikes.",files:["dates_sales_90_days.csv","dates_inventory_current.xlsx","gift_packaging_costs.csv"],columns:baseColumns,moneyAtRisk:121000,deadStock:38000,stockoutRiskValue:34200,marginLeak:24000,avoidablePurchases:19200,healthScore:81,inventory:[{item:"Sukari Dates 1kg",branch:"Buraidah",daysLeft:"3.2 days",risk:"High",action:"Reorder before weekend"},{item:"Khalas Dates 5kg",branch:"North Riyadh",daysLeft:"47 days",risk:"Medium",action:"Recovery Match preview"},{item:"Gift Box Premium",branch:"Buraidah",daysLeft:"5.1 days",risk:"Medium",action:"Prepare Ramadan stock"}],actions:[makeAction("dates-sukari","stockout","Sukari demand spike","ارتفاع طلب السكري","Sukari Dates 1kg may run out before weekend demand.","Reorder 180 boxes · Estimated cost: SAR 10,800",10800,18600,"Ramadan/weekend reorder draft created.","✅ Approve Reorder"),makeAction("dates-match","transfer","Recovery Match preview","مطابقة مخزون","Khalas Dates surplus may match nearby demand.","Offer 70 boxes · Potential recovery: SAR 5,600",5600,5600,"Recovery Match suggestion prepared for manual confirmation.","✅ Review Match"),makeAction("dates-margin","price","Gift margin drop","انخفاض هامش الهدايا","Gift packaging cost increased. Margin dropped by 6.5 points.","Adjust gift box price · Recovery: SAR 2,200/month",26400,2200,"Price Shield prepared.","✅ Approve Price Shield")]},
  {id:"cafe",label:"Cafe",labelAr:"مقهى",icon:Coffee,businessName:"North Riyadh Coffee",city:"Riyadh",branches:2,description:"Coffee beans, milk, bakery items, recipe cost drift, and weekend peaks.",files:["cafe_sales_90_days.csv","cafe_inventory_current.xlsx","supplier_price_changes.csv"],columns:baseColumns,moneyAtRisk:68500,deadStock:12500,stockoutRiskValue:18400,marginLeak:28800,avoidablePurchases:8800,healthScore:79,inventory:[{item:"Croissant Butter",branch:"Riyadh",daysLeft:"1.5 days",risk:"Critical",action:"Reorder today"},{item:"Fresh Cream 1L",branch:"Riyadh",daysLeft:"6 days",risk:"Medium",action:"Price Shield"},{item:"Ethiopian Beans 250g",branch:"Branch B",daysLeft:"3 days",risk:"Medium",action:"Transfer 40 bags"}],actions:[makeAction("cafe-butter","stockout","Bakery stockout","تنبيه مخزون المخبوزات","Croissant Butter may finish in 1.5 days.","Reorder 24 boxes · Estimated cost: SAR 1,920",1920,3200,"Bakery reorder drafted.","✅ Approve Reorder"),makeAction("cafe-cream","price","Cream margin drop","انخفاض هامش الكريمة","Fresh Cream supplier cost increased. Margin dropped to 17.5%.","Menu price shield · Recovery: SAR 320/month",3840,320,"Price Shield prepared.","✅ Approve Price Shield"),makeAction("cafe-transfer","transfer","Coffee bean transfer","نقل حبوب القهوة","Branch A has surplus Ethiopian Beans. Branch B may run out in 3 days.","Transfer 40 bags · Avoided purchase: SAR 1,440",1440,1440,"Transfer task created.","✅ Approve Transfer")]},
  {id:"pharmacy",label:"Pharmacy",labelAr:"صيدلية",icon:Pill,businessName:"Al-Qassim Community Pharmacy",city:"Buraidah",branches:1,description:"Expiry risk, FEFO discipline, slow-moving OTC products, and stockout prevention.",files:["pharmacy_sales_90_days.csv","pharmacy_inventory_current.xlsx","expiry_dates.xlsx"],columns:baseColumns,moneyAtRisk:94000,deadStock:41000,stockoutRiskValue:17800,marginLeak:11200,avoidablePurchases:7600,healthScore:73,inventory:[{item:"Antacid Tablets",branch:"Main Pharmacy",daysLeft:"1.4 days",risk:"Critical",action:"Reorder today"},{item:"Dermocosmetic Cream",branch:"Main Pharmacy",daysLeft:"90+ days",risk:"Low",action:"Discount campaign"},{item:"Vitamin D 5000 IU",branch:"Main Pharmacy",daysLeft:"2.1 days",risk:"High",action:"Reorder 80 units"}],actions:[makeAction("pharma-antacid","stockout","Critical stockout","تنبيه نفاد دواء","Antacid Tablets may finish in 1.4 days.","Reorder 90 units · Estimated cost: SAR 1,350",1350,2400,"Reorder action drafted. Regulated categories are excluded from Recovery Match.","✅ Approve Reorder"),makeAction("pharma-expiry","expiry","Expiry risk","قرب انتهاء الصلاحية","SAR 14,600 in products are near-expiry or slow-moving.","Start FEFO discount campaign for 9 SKUs.",14600,5200,"FEFO campaign task created.","✅ Approve Campaign"),makeAction("pharma-margin","price","OTC margin warning","تنبيه هامش المنتجات","Supplier cost changed on Vitamin D. Margin dropped by 5 points.","Price Shield · Recovery: SAR 1,100/month",13200,1100,"Price Shield prepared.","✅ Approve Price Shield")]},
  {id:"supermarket",label:"Multi-Branch Supermarket",labelAr:"سوبرماركت متعدد الفروع",icon:Store,businessName:"Abu Fahad Markets",city:"Buraidah + North Riyadh",branches:4,description:"High SKU count, branch imbalance, weekend stockouts, and purchase optimization.",files:["supermarket_sales_90_days.csv","supermarket_inventory_current.xlsx","supplier_prices_optional.csv"],columns:baseColumns,moneyAtRisk:143000,deadStock:61000,stockoutRiskValue:25300,marginLeak:18000,avoidablePurchases:9200,healthScore:82,inventory:[{item:"Almarai Fresh Milk",branch:"Buraidah",daysLeft:"1.8 days",risk:"Critical",action:"Reorder 120"},{item:"Sukari Dates 1kg",branch:"North Riyadh",daysLeft:"4.2 days",risk:"Medium",action:"Reorder before weekend"},{item:"Coffee Beans 250g",branch:"Buraidah",daysLeft:"3 days",risk:"Medium",action:"Transfer 40 bags"},{item:"Bottled Water Pack",branch:"Riyadh",daysLeft:"6.5 days",risk:"Low",action:"Monitor"}],actions:[makeAction("super-milk","stockout","Milk stockout warning","تنبيه نفاد الحليب","Almarai Fresh Milk may finish in 1.8 days.","Reorder 120 units · Estimated cost: SAR 840",840,1200,"Purchase order draft created.","✅ Approve Reorder"),makeAction("super-cream","price","Price shield warning","حماية الهامش","Supplier cost for Fresh Cream increased. Margin dropped to 17.5%.","Shelf price SAR 18.50 · Recovery: SAR 320/month",3840,320,"Price Shield prepared.","✅ Approve Price Shield"),makeAction("super-match","transfer","Recovery Match preview","مطابقة مخزون","Coffee Beans surplus may match nearby demand before buying more.","40 bags · Potential recovery: SAR 1,440",1440,1440,"Recovery Match suggestion prepared.","✅ Review Match")]},
];

export default function ProductDemoPage(){
  const [scenarioId,setScenarioId]=useState("supermarket");
  const [step,setStep]=useState<DemoStep>("before");
  const [scan,setScan]=useState(0);
  const scenario=useMemo(()=>scenarios.find(s=>s.id===scenarioId)!,[scenarioId]);
  const [actions,setActions]=useState<DemoAction[]>(scenario.actions);
  const [activeId,setActiveId]=useState(scenario.actions[0].id);
  const approved=actions.filter(a=>a.status==="approved");
  const moneyApproved=approved.reduce((n,a)=>n+a.value,0);
  const moneyRecovered=approved.reduce((n,a)=>n+a.recovery,0);
  const health=Math.min(96,scenario.healthScore+approved.length*2);
  const active=actions.find(a=>a.id===activeId)||actions[0];
  function choose(id:string){const sc=scenarios.find(s=>s.id===id)!;setScenarioId(id);setActions(sc.actions);setActiveId(sc.actions[0].id);setStep("upload");setScan(0)}
  function runScan(){setStep("scan");let i=0;setScan(0);const timer=setInterval(()=>{i++; if(i>=scanSteps.length){clearInterval(timer);setStep("audit")} else setScan(i)},560)}
  function approve(id:string){setActions(a=>a.map(x=>x.id===id?{...x,status:"approved"}:x))}
  function reject(id:string){setActions(a=>a.map(x=>x.id===id?{...x,status:"rejected"}:x))}
  function reset(){const sc=scenarios.find(s=>s.id===scenarioId)!;setActions(sc.actions);setActiveId(sc.actions[0].id);setStep("before");setScan(0)}
  return <main className="min-h-screen bg-[#0A0E0C] text-[#F4EFE6]">
    <nav className="sticky top-0 z-40 border-b border-white/10 bg-[#0A0E0C]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link href="/" className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#E0B34A] font-serif font-black text-black">ن</div><div><b className="font-serif text-xl">nazmak</b><p className="font-mono text-[9px] uppercase tracking-[.24em] text-[#CBB38A]">NazmOS recovery simulator</p></div></Link><Link href="/" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm text-white/70"><ArrowLeft className="h-4 w-4"/>Back</Link></div></nav>
    <section className="relative overflow-hidden px-5 py-12 md:py-16"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_18%,rgba(203,179,138,.20),transparent_32%),radial-gradient(circle_at_18%_85%,rgba(19,160,90,.15),transparent_34%)]"/><div className="relative mx-auto max-w-7xl"><p className="font-mono text-xs font-bold uppercase tracking-[.28em] text-[#E0B34A]">Experience one week of NazmOS</p><h1 className="mt-4 max-w-5xl font-serif text-5xl font-black leading-[.98] tracking-[-.04em] md:text-7xl">Run a Retail Recovery Simulation.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/65">Choose your store type, run a sample Money Audit, approve WhatsApp actions, and watch the weekly recovery report update.</p><div className="mt-7 grid gap-3 md:grid-cols-4"><Metric label="Money at Risk" value={formatSar(scenario.moneyAtRisk)} tone="risk"/><Metric label="Approved" value={formatSar(moneyApproved)} tone="approved"/><Metric label="Recovered" value={formatSar(moneyRecovered)} tone="recovered"/><Metric label="Health" value={`${health}/100`} tone="health"/></div></div></section>
    <section className="border-y border-white/10 bg-[#F4EFE6] px-5 py-5 text-[#0A0E0C]"><div className="mx-auto flex max-w-7xl flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="font-mono text-xs font-bold uppercase tracking-[.24em] text-[#0B6B3A]">Current scenario</p><h2 className="mt-1 font-serif text-3xl font-black">{scenario.businessName}</h2><p className="text-black/60">{scenario.label} · {scenario.city} · {scenario.branches} branches</p></div><div className="flex gap-2"><button onClick={runScan} className="rounded-2xl bg-[#0A0E0C] px-5 py-3 text-sm font-bold text-white">Run Money Audit</button><button onClick={reset} className="rounded-2xl border border-black/10 bg-white/70 px-4 py-3 text-sm font-bold"><RefreshCw className="mr-2 inline h-4 w-4"/>Reset</button></div></div></section>
    <section className="px-5 py-10"><div className="mx-auto max-w-7xl"><Stepper step={step} setStep={setStep}/>{step==="before"&&<Before setStep={setStep}/>} {step==="choose"&&<Choose scenarioId={scenarioId} choose={choose}/>} {step==="upload"&&<Upload scenario={scenario} setStep={setStep}/>} {step==="mapping"&&<Mapping scenario={scenario} runScan={runScan}/>} {step==="scan"&&<Scan scan={scan}/>} {step==="audit"&&<Audit scenario={scenario} setStep={setStep}/>} {step==="whatsapp"&&<WhatsApp actions={actions} active={active} setActive={setActiveId} approve={approve} reject={reject} setStep={setStep}/>} {step==="dashboard"&&<Dashboard scenario={scenario} actions={actions} approve={approve} reject={reject} setStep={setStep} moneyApproved={moneyApproved} moneyRecovered={moneyRecovered} health={health}/>} {step==="weekly"&&<Weekly scenario={scenario} moneyApproved={moneyApproved} moneyRecovered={moneyRecovered} health={health} setStep={setStep}/>} {step==="cta"&&<CTA/>}</div></section>
  </main>
}
function Metric({label,value,tone}:{label:string;value:string;tone:"risk"|"approved"|"recovered"|"health"}){const c={risk:"text-[#C8412A]",approved:"text-[#E0B34A]",recovered:"text-[#13A05A]",health:"text-white"}[tone];return <div className="rounded-3xl border border-white/10 bg-white/[.04] p-4"><p className="font-mono text-[10px] uppercase tracking-[.22em] text-white/45">{label}</p><p className={`mt-2 font-serif text-2xl font-black ${c}`}>{value}</p></div>}
function Stepper({step,setStep}:{step:DemoStep;setStep:(s:DemoStep)=>void}){const steps:DemoStep[]=["before","choose","upload","mapping","scan","audit","whatsapp","dashboard","weekly","cta"];return <div className="mb-8 overflow-x-auto"><div className="flex min-w-max gap-2">{steps.map((s,i)=><button key={s} onClick={()=>setStep(s)} className={`rounded-full px-3 py-2 text-xs font-bold capitalize ${step===s?"bg-[#E0B34A] text-black":"border border-white/10 text-white/50"}`}>{i+1}. {s}</button>)}</div></div>}
function Before({setStep}:{setStep:(s:DemoStep)=>void}){return <Panel title="Before NazmOS" kicker="What owners deal with now"><div className="grid gap-4 md:grid-cols-4">{["Cash stuck in dead stock","Empty shelves before weekend","Supplier costs hurting margin","Owner chasing staff on WhatsApp"].map(x=><div key={x} className="rounded-2xl bg-white/[.04] p-5 text-white/70">{x}</div>)}</div><button onClick={()=>setStep("choose")} className="mt-6 rounded-2xl bg-[#E0B34A] px-6 py-3 font-bold text-black">Choose your store type</button></Panel>}
function Choose({scenarioId,choose}:{scenarioId:string;choose:(id:string)=>void}){return <Panel title="Choose your store type" kicker="Scenario changes the whole demo"><div className="grid gap-4 md:grid-cols-5">{scenarios.map(s=>{const Icon=s.icon;return <button key={s.id} onClick={()=>choose(s.id)} className={`rounded-3xl border p-5 text-left ${scenarioId===s.id?"border-[#E0B34A] bg-[#E0B34A]/10":"border-white/10 bg-white/[.04]"}`}><Icon className="mb-4 h-6 w-6 text-[#E0B34A]"/><b>{s.label}</b><p className="mt-2 text-sm text-white/50">{s.description}</p></button>})}</div></Panel>}
function Upload({scenario,setStep}:{scenario:Scenario;setStep:(s:DemoStep)=>void}){return <Panel title="Upload sample files" kicker="No customer names needed"><div className="grid gap-4 md:grid-cols-3">{scenario.files.map(f=><div key={f} className="rounded-2xl bg-white/[.04] p-5"><FileSpreadsheet className="mb-3 h-5 w-5 text-[#13A05A]"/><b>{f}</b><p className="mt-2 text-sm text-white/50">Detected and ready</p></div>)}</div><p className="mt-5 text-white/55">No POS replacement. Your accountant can review the report.</p><button onClick={()=>setStep("mapping")} className="mt-6 rounded-2xl bg-[#E0B34A] px-6 py-3 font-bold text-black">Continue to mapping</button></Panel>}
function Mapping({scenario,runScan}:{scenario:Scenario;runScan:()=>void}){return <Panel title="NazmOS maps your columns" kicker="You confirm before analysis"><div className="grid gap-3 md:grid-cols-2">{scenario.columns.map(c=><div key={c.source} className="flex items-center justify-between rounded-2xl bg-white/[.04] p-4"><span>{c.source}</span><ArrowRight className="h-4 w-4 text-[#E0B34A]"/><b>{c.mapped}</b></div>)}</div><button onClick={runScan} className="mt-6 rounded-2xl bg-[#E0B34A] px-6 py-3 font-bold text-black">Looks correct — run audit</button></Panel>}
function Scan({scan}:{scan:number}){return <Panel title="Running Money Audit" kicker="Reading store data"><div className="space-y-3">{scanSteps.map((s,i)=><div key={s} className="flex items-center gap-3 rounded-2xl bg-white/[.04] p-4"><div className={`flex h-8 w-8 items-center justify-center rounded-full ${i<=scan?"bg-[#13A05A] text-black":"bg-white/10 text-white/40"}`}>{i<scan?<CheckCircle2 className="h-4 w-4"/>:i===scan?<Loader2 className="h-4 w-4 animate-spin"/>:i+1}</div><b className={i<=scan?"text-white":"text-white/45"}>{s}</b></div>)}</div></Panel>}
function Audit({scenario,setStep}:{scenario:Scenario;setStep:(s:DemoStep)=>void}){return <Panel title="Money Audit ready" kicker="Sample demo data"><div className="grid gap-4 md:grid-cols-3"><AuditCard label="Money at Risk" value={scenario.moneyAtRisk} color="text-[#C8412A]"/><AuditCard label="Dead Stock" value={scenario.deadStock} color="text-[#C8412A]"/><AuditCard label="Stockout Risk" value={scenario.stockoutRiskValue} color="text-[#E0B34A]"/><AuditCard label="Margin Leakage" value={scenario.marginLeak} color="text-[#E0B34A]"/><AuditCard label="Avoidable Purchases" value={scenario.avoidablePurchases} color="text-[#13A05A]"/><div className="rounded-2xl bg-white/[.04] p-5"><p className="text-white/50">Health Score</p><b className="mt-2 block font-serif text-3xl">{scenario.healthScore}/100</b></div></div><details className="mt-6 rounded-2xl bg-white/[.04] p-4"><summary className="font-bold">How did we calculate dead stock?</summary><p className="mt-3 text-white/60">Items with stock on hand and low/no sales in the analysis window are valued using cost price.</p></details><button onClick={()=>setStep("whatsapp")} className="mt-6 rounded-2xl bg-[#E0B34A] px-6 py-3 font-bold text-black">Send actions to WhatsApp</button></Panel>}
function WhatsApp({actions,active,setActive,approve,reject,setStep}:{actions:DemoAction[];active:DemoAction;setActive:(id:string)=>void;approve:(id:string)=>void;reject:(id:string)=>void;setStep:(s:DemoStep)=>void}){return <div className="grid gap-8 lg:grid-cols-2"><Panel title="WhatsApp COO" kicker="Approve like the owner"><div className="space-y-3">{actions.map(a=><button key={a.id} onClick={()=>setActive(a.id)} className={`w-full rounded-2xl border p-4 text-left ${active.id===a.id?"border-[#E0B34A] bg-[#E0B34A]/10":"border-white/10 bg-white/[.04]"}`}><b>{a.title}</b><p className="text-sm text-white/50">{formatSar(a.value)} · {a.status}</p></button>)}</div><button onClick={()=>setStep("dashboard")} className="mt-6 rounded-2xl bg-[#E0B34A] px-6 py-3 font-bold text-black">Open dashboard</button></Panel><Phone action={active} approve={()=>approve(active.id)} reject={()=>reject(active.id)}/></div>}
function Phone({action,approve,reject}:{action:DemoAction;approve:()=>void;reject:()=>void}){return <div className="mx-auto max-w-sm rounded-[2rem] bg-black p-4"><div className="rounded-[1.5rem] bg-[#0B141A] p-4"><div className="mb-4 border-b border-white/10 pb-3"><b>NazmOS</b><p className="text-xs text-white/45">by Nazmak · business account</p></div><div className="space-y-3"><div className="rounded-2xl bg-[#3D2820] p-4"><p className="text-[#ff8a73]">{action.titleAr}</p><p className="mt-2">{action.message}</p></div><div className="rounded-2xl bg-[#1F2C33] p-4"><p className="text-[#E0B34A]">Recommended Action</p><p>{action.recommendation}</p></div>{action.status==="pending"?<div className="grid gap-2 sm:grid-cols-2"><button onClick={approve} className="rounded-xl bg-[#25D366] p-3 font-bold text-black">{action.approveLabel}</button><button onClick={reject} className="rounded-xl bg-white/10 p-3 font-bold">{action.rejectLabel}</button></div>:<div className="rounded-2xl bg-white/[.06] p-4"><b>{action.status==="approved"?"Approved":"Rejected"}</b><p className="mt-2 text-sm text-white/55">{action.status==="approved"?action.consequence:"NazmOS will keep monitoring."}</p></div>}</div></div></div>}
function Dashboard({scenario,actions,approve,reject,setStep,moneyApproved,moneyRecovered,health}:{scenario:Scenario;actions:DemoAction[];approve:(id:string)=>void;reject:(id:string)=>void;setStep:(s:DemoStep)=>void;moneyApproved:number;moneyRecovered:number;health:number}){return <Panel title="Recovery Dashboard" kicker="What changed after approvals"><div className="grid gap-4 md:grid-cols-4"><Metric label="At Risk" value={formatSar(scenario.moneyAtRisk)} tone="risk"/><Metric label="Approved" value={formatSar(moneyApproved)} tone="approved"/><Metric label="Recovered" value={formatSar(moneyRecovered)} tone="recovered"/><Metric label="Health" value={`${health}/100`} tone="health"/></div><div className="mt-6 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[700px] text-sm"><thead className="bg-white/[.04] text-white/45"><tr>{["Item","Branch","Days Left","Risk","Action"].map(h=><th key={h} className="px-4 py-3 text-left">{h}</th>)}</tr></thead><tbody>{scenario.inventory.map(r=><tr key={r.item} className="border-t border-white/10"><td className="px-4 py-3">{r.item}</td><td className="px-4 py-3 text-white/60">{r.branch}</td><td className="px-4 py-3">{r.daysLeft}</td><td className="px-4 py-3 text-[#E0B34A]">{r.risk}</td><td className="px-4 py-3">{r.action}</td></tr>)}</tbody></table></div><div className="mt-6 grid gap-3 md:grid-cols-3">{actions.map(a=><div key={a.id} className="rounded-2xl bg-white/[.04] p-4"><b>{a.title}</b><p className="text-sm text-white/50">{a.status}</p>{a.status==="pending"&&<div className="mt-3 flex gap-2"><button onClick={()=>approve(a.id)} className="rounded-lg bg-[#25D366] px-3 py-2 text-xs font-bold text-black">Approve</button><button onClick={()=>reject(a.id)} className="rounded-lg bg-white/10 px-3 py-2 text-xs">Reject</button></div>}</div>)}</div><button onClick={()=>setStep("weekly")} className="mt-6 rounded-2xl bg-[#E0B34A] px-6 py-3 font-bold text-black">View weekly report</button></Panel>}
function Weekly({scenario,moneyApproved,moneyRecovered,health,setStep}:{scenario:Scenario;moneyApproved:number;moneyRecovered:number;health:number;setStep:(s:DemoStep)=>void}){const [sent,setSent]=useState("");return <Panel title="Thursday Money Report" kicker="The retention habit"><div className="grid gap-4 md:grid-cols-4"><AuditCard label="This week at risk" value={25300} color="text-[#C8412A]"/><AuditCard label="Approved" value={moneyApproved} color="text-[#E0B34A]"/><AuditCard label="Recovered" value={moneyRecovered} color="text-[#13A05A]"/><div className="rounded-2xl bg-white/[.04] p-5"><p className="text-white/50">Health</p><b className="font-serif text-3xl">{health}/100</b></div></div><div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>setSent("Sent to WhatsApp")} className="rounded-2xl bg-[#25D366] px-5 py-3 font-bold text-black">Send to WhatsApp</button><button onClick={()=>setSent("PDF prepared")} className="rounded-2xl border border-white/10 px-5 py-3 font-bold">Download PDF</button><button onClick={()=>setSent("Accountant share prepared")} className="rounded-2xl border border-white/10 px-5 py-3 font-bold">Share with accountant</button></div>{sent&&<p className="mt-4 text-[#13A05A]">✓ {sent}</p>}<button onClick={()=>setStep("cta")} className="mt-6 rounded-2xl bg-[#E0B34A] px-6 py-3 font-bold text-black">Finish demo</button></Panel>}
function CTA(){return <Panel title="You just experienced the Free Money Audit" kicker="Now run it on your real store"><div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-white/[.04] p-5"><b>Free includes</b><p className="mt-3 text-white/60">2 uploads/month, 1 Money Audit/month, mock WhatsApp, Recovery Match preview.</p></div><div className="rounded-2xl bg-white/[.04] p-5"><b>Recovery Pilot includes</b><p className="mt-3 text-white/60">Weekly reports, more uploads, action tracking, founder support, WhatsApp setup.</p></div></div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Link href="/register?intent=free-audit" className="rounded-2xl bg-[#E0B34A] px-6 py-3 text-center font-bold text-black">Get Free Money Audit</Link><Link href="/" className="rounded-2xl border border-white/10 px-6 py-3 text-center font-bold">Back to Nazmak</Link></div></Panel>}
function Panel({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode}){return <motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} className="rounded-[2rem] border border-white/10 bg-white/[.03] p-6 md:p-8"><p className="font-mono text-xs font-bold uppercase tracking-[.24em] text-[#E0B34A]">{kicker}</p><h2 className="mt-3 font-serif text-4xl font-black md:text-5xl">{title}</h2><div className="mt-6">{children}</div></motion.div>}
function AuditCard({label,value,color}:{label:string;value:number;color:string}){return <div className="rounded-2xl bg-white/[.04] p-5"><p className="text-white/50">{label}</p><b className={`mt-2 block font-serif text-3xl ${color}`}>{formatSar(value)}</b></div>}
