"""Phase C cost & architecture proof: the free audit is fully deterministic.

Zero LLM / Groq / Gemini / Anthropic call paths and zero Celery / Redis usage in
the guest-audit stack. If this fails the architecture regressed.
"""
from __future__ import annotations

import pathlib

import pytest

BACKEND = pathlib.Path(__file__).resolve().parents[1] / "app"

PHASE_C_MODULES = [
    "services/audit_core.py",
    "services/file_ingestion.py",
    "services/product_pairing.py",
    "services/workbook_loader.py",
    "services/telemetry.py",
    "services/guest_audit_service.py",
    "services/money_audit_service.py",
    "routers/guest_audit.py",
]

FORBIDDEN = [
    "openai", "groq", "gemini", "anthropic", "claude", "llm", "langchain",
    "celery", "redis", "hiredis",
]


@pytest.mark.parametrize("module_rel", PHASE_C_MODULES)
def test_phase_c_stack_has_no_ai_or_celery_module_references(module_rel):
    import re

    source = (BACKEND / module_rel).read_text(encoding="utf-8").lower()
    hits = [token for token in FORBIDDEN if re.search(rf"\b{re.escape(token)}\b", source)]
    assert not hits, f"{module_rel} references forbidden dependency: {hits}"


def test_guest_result_contains_no_ai_explanations():
    import asyncio

    from app.services.guest_audit_service import run_guest_audit

    result = asyncio.run(run_guest_audit([
        {"product_name": "Dead", "current_stock": "10", "cost_price": "5", "sell_price": "8"},
    ]))
    blob = str(result).lower()
    for phrase in ("gemini", "gpt-", "claude", "generated by ai", "ai-generated"):
        assert phrase not in blob


def test_money_audit_service_imports_shared_core():
    import app.services.money_audit_service as m

    assert m.analyze_product is not None
    assert m.ProductMetrics is not None