"""Initial schema

Revision ID: 748e4f2a4e7b
Revises: 
Create Date: 2026-07-30 20:26:59.969045

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from app.database.types import UUID


# revision identifiers, used by Alembic.
revision: str = '748e4f2a4e7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', UUID(as_uuid=True), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.String(length=30), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_category', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', UUID(as_uuid=True), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('request_id', UUID(as_uuid=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_action', 'audit_log', ['action_type', 'created_at'], unique=False)
    op.create_index('idx_audit_log_business', 'audit_log', ['business_id', 'created_at'], unique=False)
    op.create_index('idx_audit_log_user', 'audit_log', ['user_id', 'created_at'], unique=False)
    op.create_table('permission_definitions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('requires_plan', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sfda_recalls',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('drug_code', sa.String(length=100), nullable=False),
    sa.Column('drug_name_ar', sa.String(length=255), nullable=True),
    sa.Column('drug_name_en', sa.String(length=255), nullable=True),
    sa.Column('recall_date', sa.Date(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('action_required', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sfda_code', 'sfda_recalls', ['drug_code'], unique=False)
    op.create_index(op.f('ix_sfda_recalls_drug_code'), 'sfda_recalls', ['drug_code'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('min_order_sar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('delivery_days', sa.String(length=50), nullable=True),
    sa.Column('total_shops_ordering', sa.Integer(), nullable=True),
    sa.Column('total_monthly_volume_sar', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suppliers_city_category', 'suppliers', ['city', 'category'], unique=False)
    op.create_table('users',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_secret', sa.String(), nullable=True),
    sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'manager', 'staff', 'admin')", name='user_role_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('organizations',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('owner_id', UUID(as_uuid=True), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.Column('default_timezone', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('businesses',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('owner_id', UUID(as_uuid=True), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('llm_usage_tokens', sa.BigInteger(), nullable=True),
    sa.Column('llm_requests_today', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('last_forecast_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', UUID(as_uuid=True), nullable=True),
    sa.Column('location_code', sa.String(length=20), nullable=True),
    sa.Column('location_name', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('is_headquarters', sa.Boolean(), nullable=True),
    sa.Column('operating_hours', sa.JSON(), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('cr_number', sa.String(length=20), nullable=True),
    sa.Column('wasfaty_id', sa.String(length=30), nullable=True),
    sa.CheckConstraint("type IN ('supermart', 'cafe', 'retail', 'hotel', 'restaurant', 'pharmacy', 'grocery', 'baqala')", name='business_type_check'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_business_owner', 'businesses', ['owner_id'], unique=False)
    op.create_index('idx_businesses_organization', 'businesses', ['organization_id'], unique=False)
    op.create_table('agent_actions',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('urgency_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_ar', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('summary_ar', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('estimated_value_sar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_savings_sar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('autonomy_dial_at_creation', sa.Integer(), nullable=False),
    sa.Column('was_auto_executed', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', UUID(as_uuid=True), nullable=True),
    sa.Column('decision_note', sa.String(), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_status', sa.String(length=30), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_actions_business_status', 'agent_actions', ['business_id', 'status'], unique=False)
    op.create_index('idx_agent_actions_created', 'agent_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_actions_business_id'), 'agent_actions', ['business_id'], unique=False)
    op.create_table('analytics_cache',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('analytics_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('computation_time_ms', sa.Integer(), nullable=True),
    sa.Column('records_analyzed', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'analytics_type', 'period_start', 'period_end', name='uq_analytics_cache_key')
    )
    op.create_table('autonomy_policies',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('dial', sa.Integer(), nullable=False),
    sa.Column('ceiling_sar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_price_increase_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_price_decrease_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('require_2fa_above_sar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_by', UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('dial >= 0 AND dial <= 100', name='autonomy_dial_range'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'action_type', name='uq_autonomy_business_action')
    )
    op.create_table('billing_events',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('stripe_event_id', sa.String(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id')
    )
    op.create_table('categories',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_category_business_name')
    )
    op.create_index('idx_category_business', 'categories', ['business_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message_count', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('total_tokens', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_sessions_business', 'chat_sessions', ['business_id'], unique=False)
    op.create_index('idx_chat_sessions_last_msg', 'chat_sessions', ['last_message_at'], unique=False)
    op.create_index('idx_chat_sessions_user', 'chat_sessions', ['user_id'], unique=False)
    op.create_table('enabled_modules',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('module_type', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('features_enabled', sa.JSON(), nullable=True),
    sa.Column('enabled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('enabled_by', UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enabled_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'module_type', name='uq_enabled_modules_business_type')
    )
    op.create_table('money_audits',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('generated_by', UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('money_at_risk_sar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('dead_stock_value_sar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stockout_risk_value_sar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margin_leakage_sar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('overstock_value_sar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('money_approved_sar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('money_recovered_sar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_quality_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('missing_data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_money_audits_business_created', 'money_audits', ['business_id', 'created_at'], unique=False)
    op.create_index('idx_money_audits_status', 'money_audits', ['status'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_number', sa.String(length=20), nullable=True),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_token', sa.String(), nullable=True),
    sa.Column('alert_preferences', sa.JSON(), nullable=True),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('max_whatsapp_per_day', sa.Integer(), nullable=True),
    sa.Column('max_sms_per_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'business_id', name='uq_notification_preferences_user_business')
    )
    op.create_table('notifications',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('body_html', sa.String(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_business', 'notifications', ['business_id'], unique=False)
    op.create_index('idx_notifications_user', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('pos_connections',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('adapter_type', sa.String(length=20), nullable=False),
    sa.Column('connection_name', sa.String(length=100), nullable=False),
    sa.Column('credentials_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('credentials_version', sa.Integer(), nullable=True),
    sa.Column('endpoint_url', sa.String(), nullable=True),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('sync_sales', sa.Boolean(), nullable=True),
    sa.Column('sync_inventory', sa.Boolean(), nullable=True),
    sa.Column('push_orders', sa.Boolean(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('last_sync_records_processed', sa.Integer(), nullable=True),
    sa.Column('last_sync_error', sa.String(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('field_mapping', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_connections_business', 'pos_connections', ['business_id'], unique=False)
    op.create_table('recovery_match_settings',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('allow_contact_reveal', sa.Boolean(), nullable=True),
    sa.Column('max_distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('allowed_categories', sa.JSON(), nullable=True),
    sa.Column('excluded_categories', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', name='uq_recovery_match_settings_business')
    )
    op.create_index('idx_recovery_match_settings_enabled', 'recovery_match_settings', ['is_enabled'], unique=False)
    op.create_table('reports',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_time_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', UUID(as_uuid=True), nullable=True),
    sa.Column('shared_with', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_business', 'reports', ['business_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('ai_queries_limit', sa.Integer(), nullable=False),
    sa.Column('locations_limit', sa.Integer(), nullable=False),
    sa.Column('team_members_limit', sa.Integer(), nullable=False),
    sa.Column('pos_integrations_limit', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index('idx_subscriptions_business', 'subscriptions', ['business_id'], unique=True)
    op.create_table('team_invitations',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=True),
    sa.Column('organization_id', UUID(as_uuid=True), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('invited_by', UUID(as_uuid=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_team_invitations_token', 'team_invitations', ['token'], unique=False)
    op.create_table('team_members',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=True),
    sa.Column('organization_id', UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', UUID(as_uuid=True), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('invited_by', UUID(as_uuid=True), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_members_business', 'team_members', ['business_id'], unique=False)
    op.create_index('idx_team_members_organization', 'team_members', ['organization_id'], unique=False)
    op.create_index('idx_team_members_user', 'team_members', ['user_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('uploaded_by', UUID(as_uuid=True), nullable=True),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('sha256_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('row_count_raw', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('row_count_imported', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('row_count_failed', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('detected_columns', sa.JSON(), nullable=True),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('sample_rows', sa.JSON(), nullable=True),
    sa.Column('date_range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.String(), nullable=True),
    sa.Column('scan_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mapping_saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etl_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etl_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uploaded_files_business', 'uploaded_files', ['business_id'], unique=False)
    op.create_index('idx_uploaded_files_created', 'uploaded_files', ['created_at'], unique=False)
    op.create_index('idx_uploaded_files_status', 'uploaded_files', ['status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('session_id', UUID(as_uuid=True), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('content_tokens', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('prompt_tokens', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('completion_tokens', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('latency_ms', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('finish_reason', sa.String(length=30), nullable=True),
    sa.Column('decisions', sa.JSON(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.String(length=10), nullable=True),
    sa.Column('feedback_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='chat_message_role_check'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_chat_messages_session', 'chat_messages', ['session_id'], unique=False)
    op.create_table('items',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('category_id', UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_forecasted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forecast_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('competitor_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('competitor_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_elasticity', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('last_price_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_change_count_30d', sa.Integer(), nullable=True),
    sa.Column('shariah_status', sa.String(length=30), nullable=True),
    sa.Column('shariah_flags', sa.JSON(), nullable=True),
    sa.Column('shariah_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('pack_size', sa.String(length=50), nullable=True),
    sa.Column('storage_type', sa.String(length=30), nullable=True),
    sa.CheckConstraint('cost_price >= 0', name='item_cost_price_check'),
    sa.CheckConstraint('sell_price >= 0', name='item_sell_price_check'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_business', 'items', ['business_id'], unique=False)
    op.create_index('idx_item_business_name', 'items', ['business_id', 'name'], unique=False)
    op.create_index('idx_item_category', 'items', ['category_id'], unique=False)
    op.create_index('idx_item_sku', 'items', ['sku'], unique=False)
    op.create_table('pos_sync_logs',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('connection_id', UUID(as_uuid=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('raw_response_sample', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['pos_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pos_sync_logs_connection', 'pos_sync_logs', ['connection_id', 'started_at'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('supplier_id', UUID(as_uuid=True), nullable=True),
    sa.Column('agent_action_id', UUID(as_uuid=True), nullable=True),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('total_sar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('items_json', sa.JSON(), nullable=False),
    sa.Column('whatsapp_message_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_agent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_action_id'], ['agent_actions.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_index('idx_po_business', 'purchase_orders', ['business_id', 'created_at'], unique=False)
    op.create_index('idx_po_supplier', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('subscription_usage',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('subscription_id', UUID(as_uuid=True), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('ai_queries_used', sa.Integer(), nullable=True),
    sa.Column('decisions_applied', sa.Integer(), nullable=True),
    sa.Column('notifications_sent', sa.Integer(), nullable=True),
    sa.Column('llm_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_completion_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'usage_date', name='uq_subscription_usage_date')
    )
    op.create_table('daily_summaries',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_transactions', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('top_item_id', UUID(as_uuid=True), nullable=True),
    sa.Column('top_item_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['top_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'date', name='uq_daily_summary_business_date')
    )
    op.create_index('idx_daily_summary_business_date', 'daily_summaries', ['business_id', 'date'], unique=False)
    op.create_table('decision_log',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', UUID(as_uuid=True), nullable=True),
    sa.Column('chat_message_id', UUID(as_uuid=True), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('item_id', UUID(as_uuid=True), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('by_when', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('raw_output', sa.JSON(), nullable=True),
    sa.Column('was_applied', sa.Boolean(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_outcome', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decision_log_action', 'decision_log', ['action_type'], unique=False)
    op.create_index('idx_decision_log_business', 'decision_log', ['business_id'], unique=False)
    op.create_index('idx_decision_log_created', 'decision_log', ['created_at'], unique=False)
    op.create_table('forecast_cache',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('item_id', UUID(as_uuid=True), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('training_rows', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('training_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mape_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rmse_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('forecast_7d', sa.JSON(), nullable=False),
    sa.Column('forecast_30d', sa.JSON(), nullable=False),
    sa.Column('weekly_pattern', sa.JSON(), nullable=False),
    sa.Column('trend_direction', sa.String(length=10), nullable=True),
    sa.Column('trend_strength', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'item_id', name='uq_forecast_cache_business_item')
    )
    op.create_index('idx_forecast_cache_business', 'forecast_cache', ['business_id'], unique=False)
    op.create_index('idx_forecast_cache_expires', 'forecast_cache', ['expires_at'], unique=False)
    op.create_table('inventory',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('item_id', UUID(as_uuid=True), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_stock', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_restocked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forecasted_demand_7d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('forecasted_demand_30d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('forecast_confidence', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=True),
    sa.Column('anomaly_detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('supplier_id', UUID(as_uuid=True), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('safety_stock', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('economic_order_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_stockout_date', sa.Date(), nullable=True),
    sa.Column('stockout_count_90d', sa.Integer(), nullable=True),
    sa.CheckConstraint('current_stock >= 0', name='inventory_stock_check'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'item_id', name='uq_inventory_business_item')
    )
    op.create_index('idx_inventory_business', 'inventory', ['business_id'], unique=False)
    op.create_index('idx_inventory_item', 'inventory', ['item_id'], unique=False)
    op.create_table('money_audit_actions',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('audit_id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('item_id', UUID(as_uuid=True), nullable=True),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expected_recovery_sar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recommended_discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('approval_channel', sa.String(length=30), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_value_sar', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['money_audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_money_audit_actions_audit', 'money_audit_actions', ['audit_id'], unique=False)
    op.create_index('idx_money_audit_actions_business_status', 'money_audit_actions', ['business_id', 'status'], unique=False)
    op.create_index('idx_money_audit_actions_item', 'money_audit_actions', ['item_id'], unique=False)
    op.create_table('parts_compatibility',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('item_id', UUID(as_uuid=True), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('engine_code', sa.String(length=50), nullable=True),
    sa.Column('oem_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parts_make_model', 'parts_compatibility', ['make', 'model'], unique=False)
    op.create_index('idx_parts_oem', 'parts_compatibility', ['oem_number'], unique=False)
    op.create_table('pharmacy_lots',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('item_id', UUID(as_uuid=True), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('supplier_id', UUID(as_uuid=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('days_to_expiry', sa.Integer(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('is_near_expiry', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pharmacy_lots_expiry', 'pharmacy_lots', ['business_id', 'expiry_date'], unique=False)
    op.create_index('idx_pharmacy_lots_item', 'pharmacy_lots', ['item_id'], unique=False)
    op.create_table('pricing_recommendations',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('item_id', UUID(as_uuid=True), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recommended_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recommended_margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expected_demand_change_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expected_revenue_change', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_profit_change', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_by', UUID(as_uuid=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pricing_recommendations_business', 'pricing_recommendations', ['business_id'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('item_id', UUID(as_uuid=True), nullable=True),
    sa.Column('category_id', UUID(as_uuid=True), nullable=True),
    sa.Column('apply_to_all', sa.Boolean(), nullable=True),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_adjustment_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pricing_rules_business', 'pricing_rules', ['business_id'], unique=False)
    op.create_index('idx_pricing_rules_item', 'pricing_rules', ['item_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('menu_item_id', UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('yield_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yield_unit', sa.String(length=20), nullable=True),
    sa.Column('ingredients_json', sa.JSON(), nullable=False),
    sa.Column('total_cogs_sar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('target_margin_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_cost_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'menu_item_id', name='uq_recipe_menu_item')
    )
    op.create_table('stock_recovery_listings',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('seller_business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('seller_branch_id', UUID(as_uuid=True), nullable=True),
    sa.Column('item_id', UUID(as_uuid=True), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('quantity_available', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost_sar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('asking_price_sar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('storage_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('asking_price_sar >= 0', name='stock_recovery_listing_price_nonnegative'),
    sa.CheckConstraint('quantity_available > 0', name='stock_recovery_listing_qty_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_branch_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_recovery_listings_barcode', 'stock_recovery_listings', ['barcode'], unique=False)
    op.create_index('idx_stock_recovery_listings_item', 'stock_recovery_listings', ['item_id'], unique=False)
    op.create_index('idx_stock_recovery_listings_seller_status', 'stock_recovery_listings', ['seller_business_id', 'status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('item_id', UUID(as_uuid=True), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('transaction_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("transaction_type IN ('sale', 'return', 'waste')", name='transaction_type_check'),
    sa.CheckConstraint('quantity > 0', name='transaction_quantity_check'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_business', 'transactions', ['business_id'], unique=False)
    op.create_index('idx_transaction_business_date', 'transactions', ['business_id', 'transaction_at'], unique=False)
    op.create_index('idx_transaction_date', 'transactions', ['transaction_at'], unique=False)
    op.create_index('idx_transaction_item', 'transactions', ['item_id'], unique=False)
    op.create_index(op.f('ix_transactions_reference_id'), 'transactions', ['reference_id'], unique=False)
    op.create_table('executed_actions',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('decision_id', UUID(as_uuid=True), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', UUID(as_uuid=True), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=False),
    sa.Column('new_state', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_by', UUID(as_uuid=True), nullable=True),
    sa.Column('external_actions', sa.JSON(), nullable=True),
    sa.Column('is_reversible', sa.Boolean(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_by', UUID(as_uuid=True), nullable=True),
    sa.Column('reversal_reason', sa.String(), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('outcome_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_id'], ['decision_log.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_executed_actions_business', 'executed_actions', ['business_id'], unique=False)
    op.create_index('idx_executed_actions_decision', 'executed_actions', ['decision_id'], unique=False)
    op.create_index('idx_executed_actions_entity', 'executed_actions', ['entity_type', 'entity_id'], unique=False)
    op.create_table('stock_recovery_matches',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('listing_id', UUID(as_uuid=True), nullable=False),
    sa.Column('buyer_business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('buyer_branch_id', UUID(as_uuid=True), nullable=True),
    sa.Column('buyer_item_id', UUID(as_uuid=True), nullable=True),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('buyer_need_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('buyer_days_left', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('seller_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buyer_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_revealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovered_value_sar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_branch_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['stock_recovery_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'buyer_business_id', 'buyer_item_id', name='uq_stock_recovery_match_unique_buyer_item')
    )
    op.create_index('idx_stock_recovery_matches_buyer_status', 'stock_recovery_matches', ['buyer_business_id', 'status'], unique=False)
    op.create_index('idx_stock_recovery_matches_listing', 'stock_recovery_matches', ['listing_id'], unique=False)
    op.create_table('stock_recovery_events',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('match_id', UUID(as_uuid=True), nullable=True),
    sa.Column('listing_id', UUID(as_uuid=True), nullable=True),
    sa.Column('actor_business_id', UUID(as_uuid=True), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['stock_recovery_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['stock_recovery_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_recovery_events_listing', 'stock_recovery_events', ['listing_id', 'created_at'], unique=False)
    op.create_index('idx_stock_recovery_events_match', 'stock_recovery_events', ['match_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_recovery_events_match', table_name='stock_recovery_events')
    op.drop_index('idx_stock_recovery_events_listing', table_name='stock_recovery_events')
    op.drop_table('stock_recovery_events')
    op.drop_index('idx_stock_recovery_matches_listing', table_name='stock_recovery_matches')
    op.drop_index('idx_stock_recovery_matches_buyer_status', table_name='stock_recovery_matches')
    op.drop_table('stock_recovery_matches')
    op.drop_index('idx_executed_actions_entity', table_name='executed_actions')
    op.drop_index('idx_executed_actions_decision', table_name='executed_actions')
    op.drop_index('idx_executed_actions_business', table_name='executed_actions')
    op.drop_table('executed_actions')
    op.drop_index(op.f('ix_transactions_reference_id'), table_name='transactions')
    op.drop_index('idx_transaction_item', table_name='transactions')
    op.drop_index('idx_transaction_date', table_name='transactions')
    op.drop_index('idx_transaction_business_date', table_name='transactions')
    op.drop_index('idx_transaction_business', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_stock_recovery_listings_seller_status', table_name='stock_recovery_listings')
    op.drop_index('idx_stock_recovery_listings_item', table_name='stock_recovery_listings')
    op.drop_index('idx_stock_recovery_listings_barcode', table_name='stock_recovery_listings')
    op.drop_table('stock_recovery_listings')
    op.drop_table('recipes')
    op.drop_index('idx_pricing_rules_item', table_name='pricing_rules')
    op.drop_index('idx_pricing_rules_business', table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index('idx_pricing_recommendations_business', table_name='pricing_recommendations')
    op.drop_table('pricing_recommendations')
    op.drop_index('idx_pharmacy_lots_item', table_name='pharmacy_lots')
    op.drop_index('idx_pharmacy_lots_expiry', table_name='pharmacy_lots')
    op.drop_table('pharmacy_lots')
    op.drop_index('idx_parts_oem', table_name='parts_compatibility')
    op.drop_index('idx_parts_make_model', table_name='parts_compatibility')
    op.drop_table('parts_compatibility')
    op.drop_index('idx_money_audit_actions_item', table_name='money_audit_actions')
    op.drop_index('idx_money_audit_actions_business_status', table_name='money_audit_actions')
    op.drop_index('idx_money_audit_actions_audit', table_name='money_audit_actions')
    op.drop_table('money_audit_actions')
    op.drop_index('idx_inventory_item', table_name='inventory')
    op.drop_index('idx_inventory_business', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('idx_forecast_cache_expires', table_name='forecast_cache')
    op.drop_index('idx_forecast_cache_business', table_name='forecast_cache')
    op.drop_table('forecast_cache')
    op.drop_index('idx_decision_log_created', table_name='decision_log')
    op.drop_index('idx_decision_log_business', table_name='decision_log')
    op.drop_index('idx_decision_log_action', table_name='decision_log')
    op.drop_table('decision_log')
    op.drop_index('idx_daily_summary_business_date', table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_table('subscription_usage')
    op.drop_index('idx_po_supplier', table_name='purchase_orders')
    op.drop_index('idx_po_business', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('idx_pos_sync_logs_connection', table_name='pos_sync_logs')
    op.drop_table('pos_sync_logs')
    op.drop_index('idx_item_sku', table_name='items')
    op.drop_index('idx_item_category', table_name='items')
    op.drop_index('idx_item_business_name', table_name='items')
    op.drop_index('idx_item_business', table_name='items')
    op.drop_table('items')
    op.drop_index('idx_chat_messages_session', table_name='chat_messages')
    op.drop_index('idx_chat_messages_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_uploaded_files_status', table_name='uploaded_files')
    op.drop_index('idx_uploaded_files_created', table_name='uploaded_files')
    op.drop_index('idx_uploaded_files_business', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index('idx_team_members_user', table_name='team_members')
    op.drop_index('idx_team_members_organization', table_name='team_members')
    op.drop_index('idx_team_members_business', table_name='team_members')
    op.drop_table('team_members')
    op.drop_index('idx_team_invitations_token', table_name='team_invitations')
    op.drop_table('team_invitations')
    op.drop_index('idx_subscriptions_business', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_reports_business', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_recovery_match_settings_enabled', table_name='recovery_match_settings')
    op.drop_table('recovery_match_settings')
    op.drop_index('idx_pos_connections_business', table_name='pos_connections')
    op.drop_table('pos_connections')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_index('idx_notifications_business', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    op.drop_index('idx_money_audits_status', table_name='money_audits')
    op.drop_index('idx_money_audits_business_created', table_name='money_audits')
    op.drop_table('money_audits')
    op.drop_table('enabled_modules')
    op.drop_index('idx_chat_sessions_user', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_last_msg', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_business', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('idx_category_business', table_name='categories')
    op.drop_table('categories')
    op.drop_table('billing_events')
    op.drop_table('autonomy_policies')
    op.drop_table('analytics_cache')
    op.drop_index(op.f('ix_agent_actions_business_id'), table_name='agent_actions')
    op.drop_index('idx_agent_actions_created', table_name='agent_actions')
    op.drop_index('idx_agent_actions_business_status', table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index('idx_businesses_organization', table_name='businesses')
    op.drop_index('idx_business_owner', table_name='businesses')
    op.drop_table('businesses')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_suppliers_city_category', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_sfda_recalls_drug_code'), table_name='sfda_recalls')
    op.drop_index('idx_sfda_code', table_name='sfda_recalls')
    op.drop_table('sfda_recalls')
    op.drop_table('permission_definitions')
    op.drop_index('idx_audit_log_user', table_name='audit_log')
    op.drop_index('idx_audit_log_business', table_name='audit_log')
    op.drop_index('idx_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
