"""add_feature_flags

Revision ID: f208bd0ef3f1
Revises: 748e4f2a4e7b
Create Date: 2026-08-03 16:13:09.981384

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from app.database.types import UUID


# revision identifiers, used by Alembic.
revision: str = 'f208bd0ef3f1'
down_revision: Union[str, None] = '748e4f2a4e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('default_value', sa.Boolean(), nullable=False),
    sa.Column('allowed_plans', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feature_flags_key', 'feature_flags', ['key'], unique=False)
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    op.create_table('feature_flag_overrides',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('feature_flag_id', UUID(as_uuid=True), nullable=False),
    sa.Column('business_id', UUID(as_uuid=True), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_flag_id', 'business_id', name='uq_feature_flag_business')
    )
    op.create_index('idx_feature_flag_overrides_business', 'feature_flag_overrides', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_feature_flag_overrides_business', table_name='feature_flag_overrides')
    op.drop_table('feature_flag_overrides')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_index('idx_feature_flags_key', table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
