"""add_idempotency_keys

Revision ID: fbcd840f72b7
Revises: f208bd0ef3f1
Create Date: 2026-08-03 16:23:53.212168

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from app.database.types import UUID


# revision identifiers, used by Alembic.
revision: str = 'fbcd840f72b7'
down_revision: Union[str, None] = 'f208bd0ef3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('scope_method', sa.String(length=10), nullable=False),
    sa.Column('scope_path', sa.String(length=500), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', 'scope_method', 'scope_path', name='uq_idempotency_scope')
    )
    op.create_index('idx_idempotency_expires', 'idempotency_keys', ['expires_at'], unique=False)
    op.create_index('idx_idempotency_key_lookup', 'idempotency_keys', ['idempotency_key', 'scope_method', 'scope_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_idempotency_key_lookup', table_name='idempotency_keys')
    op.drop_index('idx_idempotency_expires', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
