"""V12 AI-OFF Reality Test - Phase 9/10 evaluator.

Computes, for every GT SKU, the DB-derived classification (using the same
windows the money audit uses, anchored at T0 = MAX(transaction_at)) and the
actual money-audit action, then compares against:
  - results/v12/ground_truth.json      (independently authored intent)
  - sample_data/v12/master_expected.csv (realized expectation)
and reports financial-integrity assertions (no leakage / no fabricated
recovery / no AI).

Step 1 (do once, from data files): prints a JSON blob is produced by a SQL
probe; this module reads the .csv generated by generate_v12_data and the
audit_current.json saved by run_pipeline / the manual audit step.

Output: results/v12/evidence/evaluation.json + console table.
"""
import csv
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
EVID = os.path.join(ROOT, "results", "v12", "evidence")
BP = "6d5312ba-c4c3-4e15-bacc-ab29a85adfa7"
T0 = "2026-06-15"

# ---- load GT + master ----
gt = json.load(open(os.path.join(ROOT, "results", "v12", "ground_truth.json"), encoding="utf-8"))
gt_by_sku = {c["sku"]: c for c in gt["cases"]}

master = {}
with open(os.path.join(ROOT, "sample_data", "v12", "master_expected.csv"), encoding="utf-8") as fh:
    for r in csv.DictReader(fh):
        master[r["sku"]] = r

# ---- per-item DB aggregates (supplied externally as JSON) ----
# expected file: evidence/db_item_metrics.json  [{sku, stock, cost, sell, qty30, prior, dsls, months:{YYYY-M:n}}]
dbm_path = os.path.join(EVID, "db_item_metrics.json")
db_metrics = {}
if os.path.exists(dbm_path):
    for r in json.load(open(dbm_path, encoding="utf-8")):
        db_metrics[r["sku"]] = r

# ---- actions from audit_current.json ----
audit = json.load(open(os.path.join(EVID, "audit_current.json"), encoding="utf-8"))
audit = audit.get("audit", audit)
summary = audit.get("summary")
if isinstance(summary, str):
    summary = json.loads(summary)
actions = audit.get("actions", [])
act_by_item = {}
for a in actions:
    ev = a.get("evidence") or {}
    if isinstance(ev, str):
        try:
            ev = json.loads(ev)
        except Exception:
            ev = {}
    act_by_item[a.get("item_id")] = {
        "action_type": a.get("action_type"),
        "title": a.get("title"),
        "classification": ev.get("classification"),
        "status": a.get("status"),
        "recoverable_high_sar": a.get("recoverable_value_high_sar"),
        "expected_recovery_sar": a.get("expected_recovery_sar"),
    }

# ---- ported classify ----
def classify(*, stock, q30, prior, dsls, months):
    from decimal import Decimal as D
    daily = q30 / D("30") if q30 > 0 else D("0")
    if q30 > 0 and months and len(months) >= 2:
        tot = sum(max(m, D("0")) for m in months)
        if tot > 0:
            peak = max(months)
            if (peak / tot) >= D("0.60"):
                return "SEASONAL"
    if q30 <= 0:
        is_dormant = (dsls is None) or (dsls is not None and dsls >= 60)
        if is_dormant and prior <= 0:
            return "DEAD"
        return "UNKNOWN"
    if stock <= 0 and daily > 0 and daily < D("3"):
        return "SLOW MOVING"
    if stock <= 0:
        return "HEALTHY"
    if daily >= D("1"):
        return "FAST"
    return "HEALTHY"
